// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/application.dart';
import 'api/error.dart';
import 'api/image_to_pdf.dart';
import 'api/merge_pdf.dart';
import 'api/pdf_export.dart';
import 'api/pdf_preview.dart';

import 'dart:async';
import 'dart:convert';

import 'frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  RustStreamSink<ImagePdfUpdate> dco_decode_StreamSink_image_pdf_update_Sse(
    dynamic raw,
  );

  @protected
  RustStreamSink<MergePdfUpdate> dco_decode_StreamSink_merge_pdf_update_Sse(
    dynamic raw,
  );

  @protected
  RustStreamSink<PdfBatchExportUpdate>
  dco_decode_StreamSink_pdf_batch_export_update_Sse(dynamic raw);

  @protected
  RustStreamSink<PdfExportUpdate> dco_decode_StreamSink_pdf_export_update_Sse(
    dynamic raw,
  );

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  ApplicationError dco_decode_application_error(dynamic raw);

  @protected
  ApplicationErrorCode dco_decode_application_error_code(dynamic raw);

  @protected
  ApplicationInfo dco_decode_application_info(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  ApplicationError dco_decode_box_autoadd_application_error(dynamic raw);

  @protected
  CreateImagePdfRequest dco_decode_box_autoadd_create_image_pdf_request(
    dynamic raw,
  );

  @protected
  ExportPdfBatchRequest dco_decode_box_autoadd_export_pdf_batch_request(
    dynamic raw,
  );

  @protected
  ExportPdfToImagesRequest dco_decode_box_autoadd_export_pdf_to_images_request(
    dynamic raw,
  );

  @protected
  MergePdfRequest dco_decode_box_autoadd_merge_pdf_request(dynamic raw);

  @protected
  PdfPageSize dco_decode_box_autoadd_pdf_page_size(dynamic raw);

  @protected
  RenderPdfPageRequest dco_decode_box_autoadd_render_pdf_page_request(
    dynamic raw,
  );

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw);

  @protected
  CreateImagePdfRequest dco_decode_create_image_pdf_request(dynamic raw);

  @protected
  ExportPdfBatchRequest dco_decode_export_pdf_batch_request(dynamic raw);

  @protected
  ExportPdfToImagesRequest dco_decode_export_pdf_to_images_request(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  ImagePdfMargin dco_decode_image_pdf_margin(dynamic raw);

  @protected
  ImagePdfOrientation dco_decode_image_pdf_orientation(dynamic raw);

  @protected
  ImagePdfPageSize dco_decode_image_pdf_page_size(dynamic raw);

  @protected
  ImagePdfStatus dco_decode_image_pdf_status(dynamic raw);

  @protected
  ImagePdfUpdate dco_decode_image_pdf_update(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<PdfBatchDocumentResult> dco_decode_list_pdf_batch_document_result(
    dynamic raw,
  );

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  MergePdfRequest dco_decode_merge_pdf_request(dynamic raw);

  @protected
  MergePdfStage dco_decode_merge_pdf_stage(dynamic raw);

  @protected
  MergePdfStatus dco_decode_merge_pdf_status(dynamic raw);

  @protected
  MergePdfUpdate dco_decode_merge_pdf_update(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  ApplicationError? dco_decode_opt_box_autoadd_application_error(dynamic raw);

  @protected
  PdfPageSize? dco_decode_opt_box_autoadd_pdf_page_size(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

  @protected
  PdfBatchDestinationMode dco_decode_pdf_batch_destination_mode(dynamic raw);

  @protected
  PdfBatchDocumentResult dco_decode_pdf_batch_document_result(dynamic raw);

  @protected
  PdfBatchExportStatus dco_decode_pdf_batch_export_status(dynamic raw);

  @protected
  PdfBatchExportUpdate dco_decode_pdf_batch_export_update(dynamic raw);

  @protected
  PdfDocumentInfo dco_decode_pdf_document_info(dynamic raw);

  @protected
  PdfExportFormat dco_decode_pdf_export_format(dynamic raw);

  @protected
  PdfExportQuality dco_decode_pdf_export_quality(dynamic raw);

  @protected
  PdfExportStatus dco_decode_pdf_export_status(dynamic raw);

  @protected
  PdfExportUpdate dco_decode_pdf_export_update(dynamic raw);

  @protected
  PdfPageSize dco_decode_pdf_page_size(dynamic raw);

  @protected
  RenderPdfPageRequest dco_decode_render_pdf_page_request(dynamic raw);

  @protected
  RenderPdfPageResult dco_decode_render_pdf_page_result(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  RustStreamSink<ImagePdfUpdate> sse_decode_StreamSink_image_pdf_update_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<MergePdfUpdate> sse_decode_StreamSink_merge_pdf_update_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<PdfBatchExportUpdate>
  sse_decode_StreamSink_pdf_batch_export_update_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<PdfExportUpdate> sse_decode_StreamSink_pdf_export_update_Sse(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  ApplicationError sse_decode_application_error(SseDeserializer deserializer);

  @protected
  ApplicationErrorCode sse_decode_application_error_code(
    SseDeserializer deserializer,
  );

  @protected
  ApplicationInfo sse_decode_application_info(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  ApplicationError sse_decode_box_autoadd_application_error(
    SseDeserializer deserializer,
  );

  @protected
  CreateImagePdfRequest sse_decode_box_autoadd_create_image_pdf_request(
    SseDeserializer deserializer,
  );

  @protected
  ExportPdfBatchRequest sse_decode_box_autoadd_export_pdf_batch_request(
    SseDeserializer deserializer,
  );

  @protected
  ExportPdfToImagesRequest sse_decode_box_autoadd_export_pdf_to_images_request(
    SseDeserializer deserializer,
  );

  @protected
  MergePdfRequest sse_decode_box_autoadd_merge_pdf_request(
    SseDeserializer deserializer,
  );

  @protected
  PdfPageSize sse_decode_box_autoadd_pdf_page_size(
    SseDeserializer deserializer,
  );

  @protected
  RenderPdfPageRequest sse_decode_box_autoadd_render_pdf_page_request(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  CreateImagePdfRequest sse_decode_create_image_pdf_request(
    SseDeserializer deserializer,
  );

  @protected
  ExportPdfBatchRequest sse_decode_export_pdf_batch_request(
    SseDeserializer deserializer,
  );

  @protected
  ExportPdfToImagesRequest sse_decode_export_pdf_to_images_request(
    SseDeserializer deserializer,
  );

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  ImagePdfMargin sse_decode_image_pdf_margin(SseDeserializer deserializer);

  @protected
  ImagePdfOrientation sse_decode_image_pdf_orientation(
    SseDeserializer deserializer,
  );

  @protected
  ImagePdfPageSize sse_decode_image_pdf_page_size(SseDeserializer deserializer);

  @protected
  ImagePdfStatus sse_decode_image_pdf_status(SseDeserializer deserializer);

  @protected
  ImagePdfUpdate sse_decode_image_pdf_update(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<PdfBatchDocumentResult> sse_decode_list_pdf_batch_document_result(
    SseDeserializer deserializer,
  );

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  MergePdfRequest sse_decode_merge_pdf_request(SseDeserializer deserializer);

  @protected
  MergePdfStage sse_decode_merge_pdf_stage(SseDeserializer deserializer);

  @protected
  MergePdfStatus sse_decode_merge_pdf_status(SseDeserializer deserializer);

  @protected
  MergePdfUpdate sse_decode_merge_pdf_update(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  ApplicationError? sse_decode_opt_box_autoadd_application_error(
    SseDeserializer deserializer,
  );

  @protected
  PdfPageSize? sse_decode_opt_box_autoadd_pdf_page_size(
    SseDeserializer deserializer,
  );

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  PdfBatchDestinationMode sse_decode_pdf_batch_destination_mode(
    SseDeserializer deserializer,
  );

  @protected
  PdfBatchDocumentResult sse_decode_pdf_batch_document_result(
    SseDeserializer deserializer,
  );

  @protected
  PdfBatchExportStatus sse_decode_pdf_batch_export_status(
    SseDeserializer deserializer,
  );

  @protected
  PdfBatchExportUpdate sse_decode_pdf_batch_export_update(
    SseDeserializer deserializer,
  );

  @protected
  PdfDocumentInfo sse_decode_pdf_document_info(SseDeserializer deserializer);

  @protected
  PdfExportFormat sse_decode_pdf_export_format(SseDeserializer deserializer);

  @protected
  PdfExportQuality sse_decode_pdf_export_quality(SseDeserializer deserializer);

  @protected
  PdfExportStatus sse_decode_pdf_export_status(SseDeserializer deserializer);

  @protected
  PdfExportUpdate sse_decode_pdf_export_update(SseDeserializer deserializer);

  @protected
  PdfPageSize sse_decode_pdf_page_size(SseDeserializer deserializer);

  @protected
  RenderPdfPageRequest sse_decode_render_pdf_page_request(
    SseDeserializer deserializer,
  );

  @protected
  RenderPdfPageResult sse_decode_render_pdf_page_result(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_image_pdf_update_Sse(
    RustStreamSink<ImagePdfUpdate> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_merge_pdf_update_Sse(
    RustStreamSink<MergePdfUpdate> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_pdf_batch_export_update_Sse(
    RustStreamSink<PdfBatchExportUpdate> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_pdf_export_update_Sse(
    RustStreamSink<PdfExportUpdate> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_application_error(
    ApplicationError self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_application_error_code(
    ApplicationErrorCode self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_application_info(
    ApplicationInfo self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_application_error(
    ApplicationError self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_create_image_pdf_request(
    CreateImagePdfRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_export_pdf_batch_request(
    ExportPdfBatchRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_export_pdf_to_images_request(
    ExportPdfToImagesRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_merge_pdf_request(
    MergePdfRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_pdf_page_size(
    PdfPageSize self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_render_pdf_page_request(
    RenderPdfPageRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_create_image_pdf_request(
    CreateImagePdfRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_export_pdf_batch_request(
    ExportPdfBatchRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_export_pdf_to_images_request(
    ExportPdfToImagesRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_image_pdf_margin(
    ImagePdfMargin self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_image_pdf_orientation(
    ImagePdfOrientation self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_image_pdf_page_size(
    ImagePdfPageSize self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_image_pdf_status(
    ImagePdfStatus self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_image_pdf_update(
    ImagePdfUpdate self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_pdf_batch_document_result(
    List<PdfBatchDocumentResult> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_merge_pdf_request(
    MergePdfRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_merge_pdf_stage(MergePdfStage self, SseSerializer serializer);

  @protected
  void sse_encode_merge_pdf_status(
    MergePdfStatus self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_merge_pdf_update(
    MergePdfUpdate self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_application_error(
    ApplicationError? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_pdf_page_size(
    PdfPageSize? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_pdf_batch_destination_mode(
    PdfBatchDestinationMode self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_pdf_batch_document_result(
    PdfBatchDocumentResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_pdf_batch_export_status(
    PdfBatchExportStatus self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_pdf_batch_export_update(
    PdfBatchExportUpdate self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_pdf_document_info(
    PdfDocumentInfo self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_pdf_export_format(
    PdfExportFormat self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_pdf_export_quality(
    PdfExportQuality self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_pdf_export_status(
    PdfExportStatus self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_pdf_export_update(
    PdfExportUpdate self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_pdf_page_size(PdfPageSize self, SseSerializer serializer);

  @protected
  void sse_encode_render_pdf_page_request(
    RenderPdfPageRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_render_pdf_page_result(
    RenderPdfPageResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {}
