// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/application.dart';
import 'api/image_to_pdf.dart';
import 'api/pdf_export.dart';
import 'api/pdf_preview.dart';

import 'dart:async';
import 'dart:convert';

import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiLifecycleInitialize();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.13.0';

  @override
  int get rustContentHash => 1053760489;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'ilikepdf_bridge',
        ioDirectory: '../../crates/ilikepdf_bridge/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Stream<ImagePdfUpdate> crateApiImageToPdfCreatePdfsFromImages({
    required CreateImagePdfRequest request,
  });

  Stream<PdfBatchExportUpdate> crateApiPdfExportExportPdfBatchToImages({
    required ExportPdfBatchRequest request,
  });

  Stream<PdfExportUpdate> crateApiPdfExportExportPdfToImages({
    required ExportPdfToImagesRequest request,
  });

  Future<ApplicationInfo> crateApiApplicationGetApplicationInfo();

  Future<void> crateApiLifecycleInitialize();

  Future<PdfDocumentInfo> crateApiPdfPreviewOpenPdfDocument({
    required String sourcePath,
  });

  Future<RenderPdfPageResult> crateApiPdfPreviewRenderPdfPage({
    required RenderPdfPageRequest request,
  });
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Stream<ImagePdfUpdate> crateApiImageToPdfCreatePdfsFromImages({
    required CreateImagePdfRequest request,
  }) {
    final progressSink = RustStreamSink<ImagePdfUpdate>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_box_autoadd_create_image_pdf_request(
              request,
              serializer,
            );
            sse_encode_StreamSink_image_pdf_update_Sse(
              progressSink,
              serializer,
            );
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 1,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: null,
          ),
          constMeta: kCrateApiImageToPdfCreatePdfsFromImagesConstMeta,
          argValues: [request, progressSink],
          apiImpl: this,
        ),
      ),
    );
    return progressSink.stream;
  }

  TaskConstMeta get kCrateApiImageToPdfCreatePdfsFromImagesConstMeta =>
      const TaskConstMeta(
        debugName: "create_pdfs_from_images",
        argNames: ["request", "progressSink"],
      );

  @override
  Stream<PdfBatchExportUpdate> crateApiPdfExportExportPdfBatchToImages({
    required ExportPdfBatchRequest request,
  }) {
    final progressSink = RustStreamSink<PdfBatchExportUpdate>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_box_autoadd_export_pdf_batch_request(
              request,
              serializer,
            );
            sse_encode_StreamSink_pdf_batch_export_update_Sse(
              progressSink,
              serializer,
            );
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 2,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: null,
          ),
          constMeta: kCrateApiPdfExportExportPdfBatchToImagesConstMeta,
          argValues: [request, progressSink],
          apiImpl: this,
        ),
      ),
    );
    return progressSink.stream;
  }

  TaskConstMeta get kCrateApiPdfExportExportPdfBatchToImagesConstMeta =>
      const TaskConstMeta(
        debugName: "export_pdf_batch_to_images",
        argNames: ["request", "progressSink"],
      );

  @override
  Stream<PdfExportUpdate> crateApiPdfExportExportPdfToImages({
    required ExportPdfToImagesRequest request,
  }) {
    final progressSink = RustStreamSink<PdfExportUpdate>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_box_autoadd_export_pdf_to_images_request(
              request,
              serializer,
            );
            sse_encode_StreamSink_pdf_export_update_Sse(
              progressSink,
              serializer,
            );
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 3,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: null,
          ),
          constMeta: kCrateApiPdfExportExportPdfToImagesConstMeta,
          argValues: [request, progressSink],
          apiImpl: this,
        ),
      ),
    );
    return progressSink.stream;
  }

  TaskConstMeta get kCrateApiPdfExportExportPdfToImagesConstMeta =>
      const TaskConstMeta(
        debugName: "export_pdf_to_images",
        argNames: ["request", "progressSink"],
      );

  @override
  Future<ApplicationInfo> crateApiApplicationGetApplicationInfo() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_application_info,
          decodeErrorData: sse_decode_application_error,
        ),
        constMeta: kCrateApiApplicationGetApplicationInfoConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiApplicationGetApplicationInfoConstMeta =>
      const TaskConstMeta(debugName: "get_application_info", argNames: []);

  @override
  Future<void> crateApiLifecycleInitialize() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiLifecycleInitializeConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLifecycleInitializeConstMeta =>
      const TaskConstMeta(debugName: "initialize", argNames: []);

  @override
  Future<PdfDocumentInfo> crateApiPdfPreviewOpenPdfDocument({
    required String sourcePath,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(sourcePath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_pdf_document_info,
          decodeErrorData: sse_decode_application_error,
        ),
        constMeta: kCrateApiPdfPreviewOpenPdfDocumentConstMeta,
        argValues: [sourcePath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPdfPreviewOpenPdfDocumentConstMeta =>
      const TaskConstMeta(
        debugName: "open_pdf_document",
        argNames: ["sourcePath"],
      );

  @override
  Future<RenderPdfPageResult> crateApiPdfPreviewRenderPdfPage({
    required RenderPdfPageRequest request,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_render_pdf_page_request(request, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_render_pdf_page_result,
          decodeErrorData: sse_decode_application_error,
        ),
        constMeta: kCrateApiPdfPreviewRenderPdfPageConstMeta,
        argValues: [request],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPdfPreviewRenderPdfPageConstMeta =>
      const TaskConstMeta(debugName: "render_pdf_page", argNames: ["request"]);

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  RustStreamSink<ImagePdfUpdate> dco_decode_StreamSink_image_pdf_update_Sse(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  RustStreamSink<PdfBatchExportUpdate>
  dco_decode_StreamSink_pdf_batch_export_update_Sse(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  RustStreamSink<PdfExportUpdate> dco_decode_StreamSink_pdf_export_update_Sse(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  ApplicationError dco_decode_application_error(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return ApplicationError(
      code: dco_decode_application_error_code(arr[0]),
      message: dco_decode_String(arr[1]),
    );
  }

  @protected
  ApplicationErrorCode dco_decode_application_error_code(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ApplicationErrorCode.values[raw as int];
  }

  @protected
  ApplicationInfo dco_decode_application_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return ApplicationInfo(
      name: dco_decode_String(arr[0]),
      version: dco_decode_String(arr[1]),
      localOnly: dco_decode_bool(arr[2]),
    );
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  ApplicationError dco_decode_box_autoadd_application_error(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_application_error(raw);
  }

  @protected
  CreateImagePdfRequest dco_decode_box_autoadd_create_image_pdf_request(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_create_image_pdf_request(raw);
  }

  @protected
  ExportPdfBatchRequest dco_decode_box_autoadd_export_pdf_batch_request(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_export_pdf_batch_request(raw);
  }

  @protected
  ExportPdfToImagesRequest dco_decode_box_autoadd_export_pdf_to_images_request(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_export_pdf_to_images_request(raw);
  }

  @protected
  PdfPageSize dco_decode_box_autoadd_pdf_page_size(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_pdf_page_size(raw);
  }

  @protected
  RenderPdfPageRequest dco_decode_box_autoadd_render_pdf_page_request(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_render_pdf_page_request(raw);
  }

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  CreateImagePdfRequest dco_decode_create_image_pdf_request(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return CreateImagePdfRequest(
      sourcePaths: dco_decode_list_String(arr[0]),
      destinationDirectory: dco_decode_String(arr[1]),
      pageSize: dco_decode_image_pdf_page_size(arr[2]),
      orientation: dco_decode_image_pdf_orientation(arr[3]),
      margin: dco_decode_image_pdf_margin(arr[4]),
      merge: dco_decode_bool(arr[5]),
    );
  }

  @protected
  ExportPdfBatchRequest dco_decode_export_pdf_batch_request(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return ExportPdfBatchRequest(
      sourcePaths: dco_decode_list_String(arr[0]),
      destinationMode: dco_decode_pdf_batch_destination_mode(arr[1]),
      customDestinationDirectory: dco_decode_opt_String(arr[2]),
      quality: dco_decode_pdf_export_quality(arr[3]),
      format: dco_decode_pdf_export_format(arr[4]),
    );
  }

  @protected
  ExportPdfToImagesRequest dco_decode_export_pdf_to_images_request(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return ExportPdfToImagesRequest(
      sourcePath: dco_decode_String(arr[0]),
      destinationDirectory: dco_decode_String(arr[1]),
      quality: dco_decode_pdf_export_quality(arr[2]),
      format: dco_decode_pdf_export_format(arr[3]),
    );
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  ImagePdfMargin dco_decode_image_pdf_margin(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ImagePdfMargin.values[raw as int];
  }

  @protected
  ImagePdfOrientation dco_decode_image_pdf_orientation(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ImagePdfOrientation.values[raw as int];
  }

  @protected
  ImagePdfPageSize dco_decode_image_pdf_page_size(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ImagePdfPageSize.values[raw as int];
  }

  @protected
  ImagePdfStatus dco_decode_image_pdf_status(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ImagePdfStatus.values[raw as int];
  }

  @protected
  ImagePdfUpdate dco_decode_image_pdf_update(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return ImagePdfUpdate(
      status: dco_decode_image_pdf_status(arr[0]),
      totalImageCount: dco_decode_u_32(arr[1]),
      completedImageCount: dco_decode_u_32(arr[2]),
      currentImage: dco_decode_opt_box_autoadd_u_32(arr[3]),
      outputFiles: dco_decode_list_String(arr[4]),
      error: dco_decode_opt_box_autoadd_application_error(arr[5]),
    );
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<PdfBatchDocumentResult> dco_decode_list_pdf_batch_document_result(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>)
        .map(dco_decode_pdf_batch_document_result)
        .toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  ApplicationError? dco_decode_opt_box_autoadd_application_error(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_application_error(raw);
  }

  @protected
  PdfPageSize? dco_decode_opt_box_autoadd_pdf_page_size(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_pdf_page_size(raw);
  }

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_32(raw);
  }

  @protected
  PdfBatchDestinationMode dco_decode_pdf_batch_destination_mode(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return PdfBatchDestinationMode.values[raw as int];
  }

  @protected
  PdfBatchDocumentResult dco_decode_pdf_batch_document_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return PdfBatchDocumentResult(
      sourcePath: dco_decode_String(arr[0]),
      displayName: dco_decode_String(arr[1]),
      totalPageCount: dco_decode_u_32(arr[2]),
      completedPageCount: dco_decode_u_32(arr[3]),
      outputFiles: dco_decode_list_String(arr[4]),
      error: dco_decode_opt_box_autoadd_application_error(arr[5]),
    );
  }

  @protected
  PdfBatchExportStatus dco_decode_pdf_batch_export_status(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return PdfBatchExportStatus.values[raw as int];
  }

  @protected
  PdfBatchExportUpdate dco_decode_pdf_batch_export_update(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 12)
      throw Exception('unexpected arr length: expect 12 but see ${arr.length}');
    return PdfBatchExportUpdate(
      status: dco_decode_pdf_batch_export_status(arr[0]),
      totalDocumentCount: dco_decode_u_32(arr[1]),
      completedDocumentCount: dco_decode_u_32(arr[2]),
      succeededDocumentCount: dco_decode_u_32(arr[3]),
      failedDocumentCount: dco_decode_u_32(arr[4]),
      currentDocumentIndex: dco_decode_opt_box_autoadd_u_32(arr[5]),
      currentDocumentFilename: dco_decode_opt_String(arr[6]),
      totalPageCount: dco_decode_u_32(arr[7]),
      completedPageCount: dco_decode_u_32(arr[8]),
      currentPage: dco_decode_opt_box_autoadd_u_32(arr[9]),
      documents: dco_decode_list_pdf_batch_document_result(arr[10]),
      error: dco_decode_opt_box_autoadd_application_error(arr[11]),
    );
  }

  @protected
  PdfDocumentInfo dco_decode_pdf_document_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return PdfDocumentInfo(
      pageCount: dco_decode_u_32(arr[0]),
      firstPageSize: dco_decode_opt_box_autoadd_pdf_page_size(arr[1]),
    );
  }

  @protected
  PdfExportFormat dco_decode_pdf_export_format(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return PdfExportFormat.values[raw as int];
  }

  @protected
  PdfExportQuality dco_decode_pdf_export_quality(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return PdfExportQuality.values[raw as int];
  }

  @protected
  PdfExportStatus dco_decode_pdf_export_status(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return PdfExportStatus.values[raw as int];
  }

  @protected
  PdfExportUpdate dco_decode_pdf_export_update(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return PdfExportUpdate(
      status: dco_decode_pdf_export_status(arr[0]),
      totalPageCount: dco_decode_u_32(arr[1]),
      completedPageCount: dco_decode_u_32(arr[2]),
      currentPage: dco_decode_opt_box_autoadd_u_32(arr[3]),
      outputFiles: dco_decode_list_String(arr[4]),
      error: dco_decode_opt_box_autoadd_application_error(arr[5]),
    );
  }

  @protected
  PdfPageSize dco_decode_pdf_page_size(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return PdfPageSize(
      widthPoints: dco_decode_f_64(arr[0]),
      heightPoints: dco_decode_f_64(arr[1]),
    );
  }

  @protected
  RenderPdfPageRequest dco_decode_render_pdf_page_request(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return RenderPdfPageRequest(
      sourcePath: dco_decode_String(arr[0]),
      pageIndex: dco_decode_u_32(arr[1]),
      targetWidth: dco_decode_u_32(arr[2]),
      destinationPath: dco_decode_opt_String(arr[3]),
    );
  }

  @protected
  RenderPdfPageResult dco_decode_render_pdf_page_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return RenderPdfPageResult(
      outputPath: dco_decode_String(arr[0]),
      widthPixels: dco_decode_u_32(arr[1]),
      heightPixels: dco_decode_u_32(arr[2]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  RustStreamSink<ImagePdfUpdate> sse_decode_StreamSink_image_pdf_update_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  RustStreamSink<PdfBatchExportUpdate>
  sse_decode_StreamSink_pdf_batch_export_update_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  RustStreamSink<PdfExportUpdate> sse_decode_StreamSink_pdf_export_update_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  ApplicationError sse_decode_application_error(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_code = sse_decode_application_error_code(deserializer);
    var var_message = sse_decode_String(deserializer);
    return ApplicationError(code: var_code, message: var_message);
  }

  @protected
  ApplicationErrorCode sse_decode_application_error_code(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return ApplicationErrorCode.values[inner];
  }

  @protected
  ApplicationInfo sse_decode_application_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_name = sse_decode_String(deserializer);
    var var_version = sse_decode_String(deserializer);
    var var_localOnly = sse_decode_bool(deserializer);
    return ApplicationInfo(
      name: var_name,
      version: var_version,
      localOnly: var_localOnly,
    );
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  ApplicationError sse_decode_box_autoadd_application_error(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_application_error(deserializer));
  }

  @protected
  CreateImagePdfRequest sse_decode_box_autoadd_create_image_pdf_request(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_create_image_pdf_request(deserializer));
  }

  @protected
  ExportPdfBatchRequest sse_decode_box_autoadd_export_pdf_batch_request(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_export_pdf_batch_request(deserializer));
  }

  @protected
  ExportPdfToImagesRequest sse_decode_box_autoadd_export_pdf_to_images_request(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_export_pdf_to_images_request(deserializer));
  }

  @protected
  PdfPageSize sse_decode_box_autoadd_pdf_page_size(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_pdf_page_size(deserializer));
  }

  @protected
  RenderPdfPageRequest sse_decode_box_autoadd_render_pdf_page_request(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_render_pdf_page_request(deserializer));
  }

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_32(deserializer));
  }

  @protected
  CreateImagePdfRequest sse_decode_create_image_pdf_request(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_sourcePaths = sse_decode_list_String(deserializer);
    var var_destinationDirectory = sse_decode_String(deserializer);
    var var_pageSize = sse_decode_image_pdf_page_size(deserializer);
    var var_orientation = sse_decode_image_pdf_orientation(deserializer);
    var var_margin = sse_decode_image_pdf_margin(deserializer);
    var var_merge = sse_decode_bool(deserializer);
    return CreateImagePdfRequest(
      sourcePaths: var_sourcePaths,
      destinationDirectory: var_destinationDirectory,
      pageSize: var_pageSize,
      orientation: var_orientation,
      margin: var_margin,
      merge: var_merge,
    );
  }

  @protected
  ExportPdfBatchRequest sse_decode_export_pdf_batch_request(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_sourcePaths = sse_decode_list_String(deserializer);
    var var_destinationMode = sse_decode_pdf_batch_destination_mode(
      deserializer,
    );
    var var_customDestinationDirectory = sse_decode_opt_String(deserializer);
    var var_quality = sse_decode_pdf_export_quality(deserializer);
    var var_format = sse_decode_pdf_export_format(deserializer);
    return ExportPdfBatchRequest(
      sourcePaths: var_sourcePaths,
      destinationMode: var_destinationMode,
      customDestinationDirectory: var_customDestinationDirectory,
      quality: var_quality,
      format: var_format,
    );
  }

  @protected
  ExportPdfToImagesRequest sse_decode_export_pdf_to_images_request(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_sourcePath = sse_decode_String(deserializer);
    var var_destinationDirectory = sse_decode_String(deserializer);
    var var_quality = sse_decode_pdf_export_quality(deserializer);
    var var_format = sse_decode_pdf_export_format(deserializer);
    return ExportPdfToImagesRequest(
      sourcePath: var_sourcePath,
      destinationDirectory: var_destinationDirectory,
      quality: var_quality,
      format: var_format,
    );
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  ImagePdfMargin sse_decode_image_pdf_margin(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return ImagePdfMargin.values[inner];
  }

  @protected
  ImagePdfOrientation sse_decode_image_pdf_orientation(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return ImagePdfOrientation.values[inner];
  }

  @protected
  ImagePdfPageSize sse_decode_image_pdf_page_size(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return ImagePdfPageSize.values[inner];
  }

  @protected
  ImagePdfStatus sse_decode_image_pdf_status(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return ImagePdfStatus.values[inner];
  }

  @protected
  ImagePdfUpdate sse_decode_image_pdf_update(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_status = sse_decode_image_pdf_status(deserializer);
    var var_totalImageCount = sse_decode_u_32(deserializer);
    var var_completedImageCount = sse_decode_u_32(deserializer);
    var var_currentImage = sse_decode_opt_box_autoadd_u_32(deserializer);
    var var_outputFiles = sse_decode_list_String(deserializer);
    var var_error = sse_decode_opt_box_autoadd_application_error(deserializer);
    return ImagePdfUpdate(
      status: var_status,
      totalImageCount: var_totalImageCount,
      completedImageCount: var_completedImageCount,
      currentImage: var_currentImage,
      outputFiles: var_outputFiles,
      error: var_error,
    );
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<PdfBatchDocumentResult> sse_decode_list_pdf_batch_document_result(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <PdfBatchDocumentResult>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_pdf_batch_document_result(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  ApplicationError? sse_decode_opt_box_autoadd_application_error(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_application_error(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PdfPageSize? sse_decode_opt_box_autoadd_pdf_page_size(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_pdf_page_size(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_32(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PdfBatchDestinationMode sse_decode_pdf_batch_destination_mode(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return PdfBatchDestinationMode.values[inner];
  }

  @protected
  PdfBatchDocumentResult sse_decode_pdf_batch_document_result(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_sourcePath = sse_decode_String(deserializer);
    var var_displayName = sse_decode_String(deserializer);
    var var_totalPageCount = sse_decode_u_32(deserializer);
    var var_completedPageCount = sse_decode_u_32(deserializer);
    var var_outputFiles = sse_decode_list_String(deserializer);
    var var_error = sse_decode_opt_box_autoadd_application_error(deserializer);
    return PdfBatchDocumentResult(
      sourcePath: var_sourcePath,
      displayName: var_displayName,
      totalPageCount: var_totalPageCount,
      completedPageCount: var_completedPageCount,
      outputFiles: var_outputFiles,
      error: var_error,
    );
  }

  @protected
  PdfBatchExportStatus sse_decode_pdf_batch_export_status(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return PdfBatchExportStatus.values[inner];
  }

  @protected
  PdfBatchExportUpdate sse_decode_pdf_batch_export_update(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_status = sse_decode_pdf_batch_export_status(deserializer);
    var var_totalDocumentCount = sse_decode_u_32(deserializer);
    var var_completedDocumentCount = sse_decode_u_32(deserializer);
    var var_succeededDocumentCount = sse_decode_u_32(deserializer);
    var var_failedDocumentCount = sse_decode_u_32(deserializer);
    var var_currentDocumentIndex = sse_decode_opt_box_autoadd_u_32(
      deserializer,
    );
    var var_currentDocumentFilename = sse_decode_opt_String(deserializer);
    var var_totalPageCount = sse_decode_u_32(deserializer);
    var var_completedPageCount = sse_decode_u_32(deserializer);
    var var_currentPage = sse_decode_opt_box_autoadd_u_32(deserializer);
    var var_documents = sse_decode_list_pdf_batch_document_result(deserializer);
    var var_error = sse_decode_opt_box_autoadd_application_error(deserializer);
    return PdfBatchExportUpdate(
      status: var_status,
      totalDocumentCount: var_totalDocumentCount,
      completedDocumentCount: var_completedDocumentCount,
      succeededDocumentCount: var_succeededDocumentCount,
      failedDocumentCount: var_failedDocumentCount,
      currentDocumentIndex: var_currentDocumentIndex,
      currentDocumentFilename: var_currentDocumentFilename,
      totalPageCount: var_totalPageCount,
      completedPageCount: var_completedPageCount,
      currentPage: var_currentPage,
      documents: var_documents,
      error: var_error,
    );
  }

  @protected
  PdfDocumentInfo sse_decode_pdf_document_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_pageCount = sse_decode_u_32(deserializer);
    var var_firstPageSize = sse_decode_opt_box_autoadd_pdf_page_size(
      deserializer,
    );
    return PdfDocumentInfo(
      pageCount: var_pageCount,
      firstPageSize: var_firstPageSize,
    );
  }

  @protected
  PdfExportFormat sse_decode_pdf_export_format(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return PdfExportFormat.values[inner];
  }

  @protected
  PdfExportQuality sse_decode_pdf_export_quality(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return PdfExportQuality.values[inner];
  }

  @protected
  PdfExportStatus sse_decode_pdf_export_status(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return PdfExportStatus.values[inner];
  }

  @protected
  PdfExportUpdate sse_decode_pdf_export_update(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_status = sse_decode_pdf_export_status(deserializer);
    var var_totalPageCount = sse_decode_u_32(deserializer);
    var var_completedPageCount = sse_decode_u_32(deserializer);
    var var_currentPage = sse_decode_opt_box_autoadd_u_32(deserializer);
    var var_outputFiles = sse_decode_list_String(deserializer);
    var var_error = sse_decode_opt_box_autoadd_application_error(deserializer);
    return PdfExportUpdate(
      status: var_status,
      totalPageCount: var_totalPageCount,
      completedPageCount: var_completedPageCount,
      currentPage: var_currentPage,
      outputFiles: var_outputFiles,
      error: var_error,
    );
  }

  @protected
  PdfPageSize sse_decode_pdf_page_size(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_widthPoints = sse_decode_f_64(deserializer);
    var var_heightPoints = sse_decode_f_64(deserializer);
    return PdfPageSize(
      widthPoints: var_widthPoints,
      heightPoints: var_heightPoints,
    );
  }

  @protected
  RenderPdfPageRequest sse_decode_render_pdf_page_request(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_sourcePath = sse_decode_String(deserializer);
    var var_pageIndex = sse_decode_u_32(deserializer);
    var var_targetWidth = sse_decode_u_32(deserializer);
    var var_destinationPath = sse_decode_opt_String(deserializer);
    return RenderPdfPageRequest(
      sourcePath: var_sourcePath,
      pageIndex: var_pageIndex,
      targetWidth: var_targetWidth,
      destinationPath: var_destinationPath,
    );
  }

  @protected
  RenderPdfPageResult sse_decode_render_pdf_page_result(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_outputPath = sse_decode_String(deserializer);
    var var_widthPixels = sse_decode_u_32(deserializer);
    var var_heightPixels = sse_decode_u_32(deserializer);
    return RenderPdfPageResult(
      outputPath: var_outputPath,
      widthPixels: var_widthPixels,
      heightPixels: var_heightPixels,
    );
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_StreamSink_image_pdf_update_Sse(
    RustStreamSink<ImagePdfUpdate> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_image_pdf_update,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_StreamSink_pdf_batch_export_update_Sse(
    RustStreamSink<PdfBatchExportUpdate> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_pdf_batch_export_update,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_StreamSink_pdf_export_update_Sse(
    RustStreamSink<PdfExportUpdate> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_pdf_export_update,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_application_error(
    ApplicationError self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_application_error_code(self.code, serializer);
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_application_error_code(
    ApplicationErrorCode self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_application_info(
    ApplicationInfo self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.version, serializer);
    sse_encode_bool(self.localOnly, serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_application_error(
    ApplicationError self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_application_error(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_create_image_pdf_request(
    CreateImagePdfRequest self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_create_image_pdf_request(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_export_pdf_batch_request(
    ExportPdfBatchRequest self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_export_pdf_batch_request(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_export_pdf_to_images_request(
    ExportPdfToImagesRequest self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_export_pdf_to_images_request(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_pdf_page_size(
    PdfPageSize self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_pdf_page_size(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_render_pdf_page_request(
    RenderPdfPageRequest self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_render_pdf_page_request(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self, serializer);
  }

  @protected
  void sse_encode_create_image_pdf_request(
    CreateImagePdfRequest self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_String(self.sourcePaths, serializer);
    sse_encode_String(self.destinationDirectory, serializer);
    sse_encode_image_pdf_page_size(self.pageSize, serializer);
    sse_encode_image_pdf_orientation(self.orientation, serializer);
    sse_encode_image_pdf_margin(self.margin, serializer);
    sse_encode_bool(self.merge, serializer);
  }

  @protected
  void sse_encode_export_pdf_batch_request(
    ExportPdfBatchRequest self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_String(self.sourcePaths, serializer);
    sse_encode_pdf_batch_destination_mode(self.destinationMode, serializer);
    sse_encode_opt_String(self.customDestinationDirectory, serializer);
    sse_encode_pdf_export_quality(self.quality, serializer);
    sse_encode_pdf_export_format(self.format, serializer);
  }

  @protected
  void sse_encode_export_pdf_to_images_request(
    ExportPdfToImagesRequest self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.sourcePath, serializer);
    sse_encode_String(self.destinationDirectory, serializer);
    sse_encode_pdf_export_quality(self.quality, serializer);
    sse_encode_pdf_export_format(self.format, serializer);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_image_pdf_margin(
    ImagePdfMargin self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_image_pdf_orientation(
    ImagePdfOrientation self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_image_pdf_page_size(
    ImagePdfPageSize self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_image_pdf_status(
    ImagePdfStatus self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_image_pdf_update(
    ImagePdfUpdate self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_image_pdf_status(self.status, serializer);
    sse_encode_u_32(self.totalImageCount, serializer);
    sse_encode_u_32(self.completedImageCount, serializer);
    sse_encode_opt_box_autoadd_u_32(self.currentImage, serializer);
    sse_encode_list_String(self.outputFiles, serializer);
    sse_encode_opt_box_autoadd_application_error(self.error, serializer);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_pdf_batch_document_result(
    List<PdfBatchDocumentResult> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_pdf_batch_document_result(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_application_error(
    ApplicationError? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_application_error(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_pdf_page_size(
    PdfPageSize? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_pdf_page_size(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_32(self, serializer);
    }
  }

  @protected
  void sse_encode_pdf_batch_destination_mode(
    PdfBatchDestinationMode self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_pdf_batch_document_result(
    PdfBatchDocumentResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.sourcePath, serializer);
    sse_encode_String(self.displayName, serializer);
    sse_encode_u_32(self.totalPageCount, serializer);
    sse_encode_u_32(self.completedPageCount, serializer);
    sse_encode_list_String(self.outputFiles, serializer);
    sse_encode_opt_box_autoadd_application_error(self.error, serializer);
  }

  @protected
  void sse_encode_pdf_batch_export_status(
    PdfBatchExportStatus self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_pdf_batch_export_update(
    PdfBatchExportUpdate self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_pdf_batch_export_status(self.status, serializer);
    sse_encode_u_32(self.totalDocumentCount, serializer);
    sse_encode_u_32(self.completedDocumentCount, serializer);
    sse_encode_u_32(self.succeededDocumentCount, serializer);
    sse_encode_u_32(self.failedDocumentCount, serializer);
    sse_encode_opt_box_autoadd_u_32(self.currentDocumentIndex, serializer);
    sse_encode_opt_String(self.currentDocumentFilename, serializer);
    sse_encode_u_32(self.totalPageCount, serializer);
    sse_encode_u_32(self.completedPageCount, serializer);
    sse_encode_opt_box_autoadd_u_32(self.currentPage, serializer);
    sse_encode_list_pdf_batch_document_result(self.documents, serializer);
    sse_encode_opt_box_autoadd_application_error(self.error, serializer);
  }

  @protected
  void sse_encode_pdf_document_info(
    PdfDocumentInfo self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.pageCount, serializer);
    sse_encode_opt_box_autoadd_pdf_page_size(self.firstPageSize, serializer);
  }

  @protected
  void sse_encode_pdf_export_format(
    PdfExportFormat self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_pdf_export_quality(
    PdfExportQuality self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_pdf_export_status(
    PdfExportStatus self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_pdf_export_update(
    PdfExportUpdate self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_pdf_export_status(self.status, serializer);
    sse_encode_u_32(self.totalPageCount, serializer);
    sse_encode_u_32(self.completedPageCount, serializer);
    sse_encode_opt_box_autoadd_u_32(self.currentPage, serializer);
    sse_encode_list_String(self.outputFiles, serializer);
    sse_encode_opt_box_autoadd_application_error(self.error, serializer);
  }

  @protected
  void sse_encode_pdf_page_size(PdfPageSize self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_64(self.widthPoints, serializer);
    sse_encode_f_64(self.heightPoints, serializer);
  }

  @protected
  void sse_encode_render_pdf_page_request(
    RenderPdfPageRequest self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.sourcePath, serializer);
    sse_encode_u_32(self.pageIndex, serializer);
    sse_encode_u_32(self.targetWidth, serializer);
    sse_encode_opt_String(self.destinationPath, serializer);
  }

  @protected
  void sse_encode_render_pdf_page_result(
    RenderPdfPageResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.outputPath, serializer);
    sse_encode_u_32(self.widthPixels, serializer);
    sse_encode_u_32(self.heightPixels, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }
}
