// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

#![allow(
    non_camel_case_types,
    unused,
    non_snake_case,
    clippy::needless_return,
    clippy::redundant_closure_call,
    clippy::redundant_closure,
    clippy::useless_conversion,
    clippy::unit_arg,
    clippy::unused_unit,
    clippy::double_parens,
    clippy::let_and_return,
    clippy::too_many_arguments,
    clippy::match_single_binding,
    clippy::clone_on_copy,
    clippy::let_unit_value,
    clippy::deref_addrof,
    clippy::explicit_auto_deref,
    clippy::borrow_deref_ref,
    clippy::uninlined_format_args,
    clippy::needless_borrow,
    mismatched_lifetime_syntaxes
)]

// Section: imports

use flutter_rust_bridge::for_generated::byteorder::{NativeEndian, ReadBytesExt, WriteBytesExt};
use flutter_rust_bridge::for_generated::{Lifetimeable, Lockable, transform_result_dco};
use flutter_rust_bridge::{Handler, IntoIntoDart};

// Section: boilerplate

flutter_rust_bridge::frb_generated_boilerplate!(
    default_stream_sink_codec = SseCodec,
    default_rust_opaque = RustOpaqueMoi,
    default_rust_auto_opaque = RustAutoOpaqueMoi,
);
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_VERSION: &str = "2.13.0";
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_CONTENT_HASH: i32 = 755409905;

// Section: executor

flutter_rust_bridge::frb_generated_default_handler!();

// Section: wire_funcs

fn wire__crate__api__image_to_pdf__create_pdfs_from_images_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "create_pdfs_from_images",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_request =
                <crate::api::image_to_pdf::CreateImagePdfRequest>::sse_decode(&mut deserializer);
            let api_progress_sink = <StreamSink<
                crate::api::image_to_pdf::ImagePdfUpdate,
                flutter_rust_bridge::for_generated::SseCodec,
            >>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let output_ok = Ok::<_, ()>({
                        crate::api::image_to_pdf::create_pdfs_from_images(
                            api_request,
                            api_progress_sink,
                        );
                    })?;
                    std::result::Result::Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__pdf_export__export_pdf_batch_to_images_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "export_pdf_batch_to_images",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_request =
                <crate::api::pdf_export::ExportPdfBatchRequest>::sse_decode(&mut deserializer);
            let api_progress_sink = <StreamSink<
                crate::api::pdf_export::PdfBatchExportUpdate,
                flutter_rust_bridge::for_generated::SseCodec,
            >>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let output_ok = Ok::<_, ()>({
                        crate::api::pdf_export::export_pdf_batch_to_images(
                            api_request,
                            api_progress_sink,
                        );
                    })?;
                    std::result::Result::Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__pdf_export__export_pdf_to_images_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "export_pdf_to_images",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_request =
                <crate::api::pdf_export::ExportPdfToImagesRequest>::sse_decode(&mut deserializer);
            let api_progress_sink = <StreamSink<
                crate::api::pdf_export::PdfExportUpdate,
                flutter_rust_bridge::for_generated::SseCodec,
            >>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let output_ok = Ok::<_, ()>({
                        crate::api::pdf_export::export_pdf_to_images(
                            api_request,
                            api_progress_sink,
                        );
                    })?;
                    std::result::Result::Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__application__get_application_info_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "get_application_info",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, crate::api::error::ApplicationError>((move || {
                    let output_ok = crate::api::application::get_application_info()?;
                    std::result::Result::Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__lifecycle__initialize_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "initialize",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let output_ok = Ok::<_, ()>({
                        crate::api::lifecycle::initialize();
                    })?;
                    std::result::Result::Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__merge_pdf__merge_pdf_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "merge_pdf",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_request =
                <crate::api::merge_pdf::MergePdfRequest>::sse_decode(&mut deserializer);
            let api_progress_sink = <StreamSink<
                crate::api::merge_pdf::MergePdfUpdate,
                flutter_rust_bridge::for_generated::SseCodec,
            >>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let output_ok = Ok::<_, ()>({
                        crate::api::merge_pdf::merge_pdf(api_request, api_progress_sink);
                    })?;
                    std::result::Result::Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__pdf_preview__open_pdf_document_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "open_pdf_document",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_source_path = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, crate::api::error::ApplicationError>((move || {
                    let output_ok = crate::api::pdf_preview::open_pdf_document(api_source_path)?;
                    std::result::Result::Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__pdf_preview__render_pdf_page_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "render_pdf_page",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_request =
                <crate::api::pdf_preview::RenderPdfPageRequest>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, crate::api::error::ApplicationError>((move || {
                    let output_ok = crate::api::pdf_preview::render_pdf_page(api_request)?;
                    std::result::Result::Ok(output_ok)
                })())
            }
        },
    )
}

// Section: dart2rust

impl SseDecode for flutter_rust_bridge::for_generated::anyhow::Error {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <String>::sse_decode(deserializer);
        return flutter_rust_bridge::for_generated::anyhow::anyhow!("{}", inner);
    }
}

impl SseDecode
    for StreamSink<
        crate::api::image_to_pdf::ImagePdfUpdate,
        flutter_rust_bridge::for_generated::SseCodec,
    >
{
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <String>::sse_decode(deserializer);
        return StreamSink::deserialize(inner);
    }
}

impl SseDecode
    for StreamSink<
        crate::api::merge_pdf::MergePdfUpdate,
        flutter_rust_bridge::for_generated::SseCodec,
    >
{
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <String>::sse_decode(deserializer);
        return StreamSink::deserialize(inner);
    }
}

impl SseDecode
    for StreamSink<
        crate::api::pdf_export::PdfBatchExportUpdate,
        flutter_rust_bridge::for_generated::SseCodec,
    >
{
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <String>::sse_decode(deserializer);
        return StreamSink::deserialize(inner);
    }
}

impl SseDecode
    for StreamSink<
        crate::api::pdf_export::PdfExportUpdate,
        flutter_rust_bridge::for_generated::SseCodec,
    >
{
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <String>::sse_decode(deserializer);
        return StreamSink::deserialize(inner);
    }
}

impl SseDecode for String {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <Vec<u8>>::sse_decode(deserializer);
        return String::from_utf8(inner).unwrap();
    }
}

impl SseDecode for crate::api::error::ApplicationError {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_code = <crate::api::error::ApplicationErrorCode>::sse_decode(deserializer);
        let mut var_message = <String>::sse_decode(deserializer);
        return crate::api::error::ApplicationError {
            code: var_code,
            message: var_message,
        };
    }
}

impl SseDecode for crate::api::error::ApplicationErrorCode {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::api::error::ApplicationErrorCode::SourceNotFound,
            1 => crate::api::error::ApplicationErrorCode::SourceNotFile,
            2 => crate::api::error::ApplicationErrorCode::SourceUnreadable,
            3 => crate::api::error::ApplicationErrorCode::InvalidPdf,
            4 => crate::api::error::ApplicationErrorCode::PageOutOfBounds,
            5 => crate::api::error::ApplicationErrorCode::InvalidRequest,
            6 => crate::api::error::ApplicationErrorCode::PdfRuntimeUnavailable,
            7 => crate::api::error::ApplicationErrorCode::StructuralPdfRuntimeUnavailable,
            8 => crate::api::error::ApplicationErrorCode::StructuralPdfRuntimeIncompatible,
            9 => crate::api::error::ApplicationErrorCode::StructuralPdfLaunchFailed,
            10 => crate::api::error::ApplicationErrorCode::PasswordRequired,
            11 => crate::api::error::ApplicationErrorCode::StructuralPdfOperationFailed,
            12 => crate::api::error::ApplicationErrorCode::StructuralPdfOutputValidationFailed,
            13 => crate::api::error::ApplicationErrorCode::InvalidOutputDirectory,
            14 => crate::api::error::ApplicationErrorCode::PermissionDenied,
            15 => crate::api::error::ApplicationErrorCode::OutputNotWritable,
            16 => crate::api::error::ApplicationErrorCode::OutputAlreadyExists,
            17 => crate::api::error::ApplicationErrorCode::OutputWriteFailed,
            18 => crate::api::error::ApplicationErrorCode::RenderingFailed,
            19 => crate::api::error::ApplicationErrorCode::EncodingFailed,
            20 => crate::api::error::ApplicationErrorCode::UnsupportedImageFormat,
            21 => crate::api::error::ApplicationErrorCode::MalformedImage,
            22 => crate::api::error::ApplicationErrorCode::ImageDecodeFailed,
            23 => crate::api::error::ApplicationErrorCode::ImageOrientationFailed,
            24 => crate::api::error::ApplicationErrorCode::DuplicateOutputName,
            25 => crate::api::error::ApplicationErrorCode::PdfDocumentCreationFailed,
            26 => crate::api::error::ApplicationErrorCode::PdfPageCreationFailed,
            27 => crate::api::error::ApplicationErrorCode::ImagePlacementFailed,
            28 => crate::api::error::ApplicationErrorCode::PdfSaveFailed,
            29 => crate::api::error::ApplicationErrorCode::Internal,
            _ => unreachable!("Invalid variant for ApplicationErrorCode: {}", inner),
        };
    }
}

impl SseDecode for crate::api::application::ApplicationInfo {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_name = <String>::sse_decode(deserializer);
        let mut var_version = <String>::sse_decode(deserializer);
        let mut var_localOnly = <bool>::sse_decode(deserializer);
        return crate::api::application::ApplicationInfo {
            name: var_name,
            version: var_version,
            local_only: var_localOnly,
        };
    }
}

impl SseDecode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap() != 0
    }
}

impl SseDecode for crate::api::image_to_pdf::CreateImagePdfRequest {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_sourcePaths = <Vec<String>>::sse_decode(deserializer);
        let mut var_destinationDirectory = <String>::sse_decode(deserializer);
        let mut var_pageSize =
            <crate::api::image_to_pdf::ImagePdfPageSize>::sse_decode(deserializer);
        let mut var_orientation =
            <crate::api::image_to_pdf::ImagePdfOrientation>::sse_decode(deserializer);
        let mut var_margin = <crate::api::image_to_pdf::ImagePdfMargin>::sse_decode(deserializer);
        let mut var_merge = <bool>::sse_decode(deserializer);
        return crate::api::image_to_pdf::CreateImagePdfRequest {
            source_paths: var_sourcePaths,
            destination_directory: var_destinationDirectory,
            page_size: var_pageSize,
            orientation: var_orientation,
            margin: var_margin,
            merge: var_merge,
        };
    }
}

impl SseDecode for crate::api::pdf_export::ExportPdfBatchRequest {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_sourcePaths = <Vec<String>>::sse_decode(deserializer);
        let mut var_destinationMode =
            <crate::api::pdf_export::PdfBatchDestinationMode>::sse_decode(deserializer);
        let mut var_customDestinationDirectory = <Option<String>>::sse_decode(deserializer);
        let mut var_quality = <crate::api::pdf_export::PdfExportQuality>::sse_decode(deserializer);
        let mut var_format = <crate::api::pdf_export::PdfExportFormat>::sse_decode(deserializer);
        return crate::api::pdf_export::ExportPdfBatchRequest {
            source_paths: var_sourcePaths,
            destination_mode: var_destinationMode,
            custom_destination_directory: var_customDestinationDirectory,
            quality: var_quality,
            format: var_format,
        };
    }
}

impl SseDecode for crate::api::pdf_export::ExportPdfToImagesRequest {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_sourcePath = <String>::sse_decode(deserializer);
        let mut var_destinationDirectory = <String>::sse_decode(deserializer);
        let mut var_quality = <crate::api::pdf_export::PdfExportQuality>::sse_decode(deserializer);
        let mut var_format = <crate::api::pdf_export::PdfExportFormat>::sse_decode(deserializer);
        return crate::api::pdf_export::ExportPdfToImagesRequest {
            source_path: var_sourcePath,
            destination_directory: var_destinationDirectory,
            quality: var_quality,
            format: var_format,
        };
    }
}

impl SseDecode for f64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_f64::<NativeEndian>().unwrap()
    }
}

impl SseDecode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_i32::<NativeEndian>().unwrap()
    }
}

impl SseDecode for crate::api::image_to_pdf::ImagePdfMargin {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::api::image_to_pdf::ImagePdfMargin::None,
            1 => crate::api::image_to_pdf::ImagePdfMargin::Small,
            2 => crate::api::image_to_pdf::ImagePdfMargin::Big,
            _ => unreachable!("Invalid variant for ImagePdfMargin: {}", inner),
        };
    }
}

impl SseDecode for crate::api::image_to_pdf::ImagePdfOrientation {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::api::image_to_pdf::ImagePdfOrientation::Portrait,
            1 => crate::api::image_to_pdf::ImagePdfOrientation::Landscape,
            _ => unreachable!("Invalid variant for ImagePdfOrientation: {}", inner),
        };
    }
}

impl SseDecode for crate::api::image_to_pdf::ImagePdfPageSize {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::api::image_to_pdf::ImagePdfPageSize::Fit,
            1 => crate::api::image_to_pdf::ImagePdfPageSize::A4,
            2 => crate::api::image_to_pdf::ImagePdfPageSize::UsLetter,
            _ => unreachable!("Invalid variant for ImagePdfPageSize: {}", inner),
        };
    }
}

impl SseDecode for crate::api::image_to_pdf::ImagePdfStatus {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::api::image_to_pdf::ImagePdfStatus::Running,
            1 => crate::api::image_to_pdf::ImagePdfStatus::Complete,
            2 => crate::api::image_to_pdf::ImagePdfStatus::Failed,
            _ => unreachable!("Invalid variant for ImagePdfStatus: {}", inner),
        };
    }
}

impl SseDecode for crate::api::image_to_pdf::ImagePdfUpdate {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_status = <crate::api::image_to_pdf::ImagePdfStatus>::sse_decode(deserializer);
        let mut var_totalImageCount = <u32>::sse_decode(deserializer);
        let mut var_completedImageCount = <u32>::sse_decode(deserializer);
        let mut var_currentImage = <Option<u32>>::sse_decode(deserializer);
        let mut var_outputFiles = <Vec<String>>::sse_decode(deserializer);
        let mut var_error = <Option<crate::api::error::ApplicationError>>::sse_decode(deserializer);
        return crate::api::image_to_pdf::ImagePdfUpdate {
            status: var_status,
            total_image_count: var_totalImageCount,
            completed_image_count: var_completedImageCount,
            current_image: var_currentImage,
            output_files: var_outputFiles,
            error: var_error,
        };
    }
}

impl SseDecode for Vec<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<String>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::api::pdf_export::PdfBatchDocumentResult> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<crate::api::pdf_export::PdfBatchDocumentResult>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<u8>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for crate::api::merge_pdf::MergePdfRequest {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_sourcePaths = <Vec<String>>::sse_decode(deserializer);
        let mut var_destinationDirectory = <String>::sse_decode(deserializer);
        let mut var_outputName = <String>::sse_decode(deserializer);
        return crate::api::merge_pdf::MergePdfRequest {
            source_paths: var_sourcePaths,
            destination_directory: var_destinationDirectory,
            output_name: var_outputName,
        };
    }
}

impl SseDecode for crate::api::merge_pdf::MergePdfStage {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::api::merge_pdf::MergePdfStage::Preparing,
            1 => crate::api::merge_pdf::MergePdfStage::Merging,
            2 => crate::api::merge_pdf::MergePdfStage::Validating,
            3 => crate::api::merge_pdf::MergePdfStage::Publishing,
            4 => crate::api::merge_pdf::MergePdfStage::Completed,
            _ => unreachable!("Invalid variant for MergePdfStage: {}", inner),
        };
    }
}

impl SseDecode for crate::api::merge_pdf::MergePdfStatus {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::api::merge_pdf::MergePdfStatus::Running,
            1 => crate::api::merge_pdf::MergePdfStatus::Complete,
            2 => crate::api::merge_pdf::MergePdfStatus::Failed,
            _ => unreachable!("Invalid variant for MergePdfStatus: {}", inner),
        };
    }
}

impl SseDecode for crate::api::merge_pdf::MergePdfUpdate {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_status = <crate::api::merge_pdf::MergePdfStatus>::sse_decode(deserializer);
        let mut var_stage = <crate::api::merge_pdf::MergePdfStage>::sse_decode(deserializer);
        let mut var_inputCount = <u32>::sse_decode(deserializer);
        let mut var_totalPageCount = <u32>::sse_decode(deserializer);
        let mut var_outputPath = <Option<String>>::sse_decode(deserializer);
        let mut var_warningInputCount = <u32>::sse_decode(deserializer);
        let mut var_hasWarnings = <bool>::sse_decode(deserializer);
        let mut var_failedInputIndex = <Option<u32>>::sse_decode(deserializer);
        let mut var_failedInputPath = <Option<String>>::sse_decode(deserializer);
        let mut var_error = <Option<crate::api::error::ApplicationError>>::sse_decode(deserializer);
        return crate::api::merge_pdf::MergePdfUpdate {
            status: var_status,
            stage: var_stage,
            input_count: var_inputCount,
            total_page_count: var_totalPageCount,
            output_path: var_outputPath,
            warning_input_count: var_warningInputCount,
            has_warnings: var_hasWarnings,
            failed_input_index: var_failedInputIndex,
            failed_input_path: var_failedInputPath,
            error: var_error,
        };
    }
}

impl SseDecode for Option<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<String>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<crate::api::error::ApplicationError> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<crate::api::error::ApplicationError>::sse_decode(
                deserializer,
            ));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<crate::api::pdf_preview::PdfPageSize> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<crate::api::pdf_preview::PdfPageSize>::sse_decode(
                deserializer,
            ));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<u32> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<u32>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for crate::api::pdf_export::PdfBatchDestinationMode {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::api::pdf_export::PdfBatchDestinationMode::NextToSourceFiles,
            1 => crate::api::pdf_export::PdfBatchDestinationMode::CustomFolder,
            _ => unreachable!("Invalid variant for PdfBatchDestinationMode: {}", inner),
        };
    }
}

impl SseDecode for crate::api::pdf_export::PdfBatchDocumentResult {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_sourcePath = <String>::sse_decode(deserializer);
        let mut var_displayName = <String>::sse_decode(deserializer);
        let mut var_totalPageCount = <u32>::sse_decode(deserializer);
        let mut var_completedPageCount = <u32>::sse_decode(deserializer);
        let mut var_outputFiles = <Vec<String>>::sse_decode(deserializer);
        let mut var_error = <Option<crate::api::error::ApplicationError>>::sse_decode(deserializer);
        return crate::api::pdf_export::PdfBatchDocumentResult {
            source_path: var_sourcePath,
            display_name: var_displayName,
            total_page_count: var_totalPageCount,
            completed_page_count: var_completedPageCount,
            output_files: var_outputFiles,
            error: var_error,
        };
    }
}

impl SseDecode for crate::api::pdf_export::PdfBatchExportStatus {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::api::pdf_export::PdfBatchExportStatus::Running,
            1 => crate::api::pdf_export::PdfBatchExportStatus::Complete,
            2 => crate::api::pdf_export::PdfBatchExportStatus::CompleteWithErrors,
            3 => crate::api::pdf_export::PdfBatchExportStatus::Failed,
            _ => unreachable!("Invalid variant for PdfBatchExportStatus: {}", inner),
        };
    }
}

impl SseDecode for crate::api::pdf_export::PdfBatchExportUpdate {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_status =
            <crate::api::pdf_export::PdfBatchExportStatus>::sse_decode(deserializer);
        let mut var_totalDocumentCount = <u32>::sse_decode(deserializer);
        let mut var_completedDocumentCount = <u32>::sse_decode(deserializer);
        let mut var_succeededDocumentCount = <u32>::sse_decode(deserializer);
        let mut var_failedDocumentCount = <u32>::sse_decode(deserializer);
        let mut var_currentDocumentIndex = <Option<u32>>::sse_decode(deserializer);
        let mut var_currentDocumentFilename = <Option<String>>::sse_decode(deserializer);
        let mut var_totalPageCount = <u32>::sse_decode(deserializer);
        let mut var_completedPageCount = <u32>::sse_decode(deserializer);
        let mut var_currentPage = <Option<u32>>::sse_decode(deserializer);
        let mut var_documents =
            <Vec<crate::api::pdf_export::PdfBatchDocumentResult>>::sse_decode(deserializer);
        let mut var_error = <Option<crate::api::error::ApplicationError>>::sse_decode(deserializer);
        return crate::api::pdf_export::PdfBatchExportUpdate {
            status: var_status,
            total_document_count: var_totalDocumentCount,
            completed_document_count: var_completedDocumentCount,
            succeeded_document_count: var_succeededDocumentCount,
            failed_document_count: var_failedDocumentCount,
            current_document_index: var_currentDocumentIndex,
            current_document_filename: var_currentDocumentFilename,
            total_page_count: var_totalPageCount,
            completed_page_count: var_completedPageCount,
            current_page: var_currentPage,
            documents: var_documents,
            error: var_error,
        };
    }
}

impl SseDecode for crate::api::pdf_preview::PdfDocumentInfo {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_pageCount = <u32>::sse_decode(deserializer);
        let mut var_firstPageSize =
            <Option<crate::api::pdf_preview::PdfPageSize>>::sse_decode(deserializer);
        return crate::api::pdf_preview::PdfDocumentInfo {
            page_count: var_pageCount,
            first_page_size: var_firstPageSize,
        };
    }
}

impl SseDecode for crate::api::pdf_export::PdfExportFormat {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::api::pdf_export::PdfExportFormat::Png,
            1 => crate::api::pdf_export::PdfExportFormat::Jpg,
            _ => unreachable!("Invalid variant for PdfExportFormat: {}", inner),
        };
    }
}

impl SseDecode for crate::api::pdf_export::PdfExportQuality {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::api::pdf_export::PdfExportQuality::Standard,
            1 => crate::api::pdf_export::PdfExportQuality::HighQuality,
            _ => unreachable!("Invalid variant for PdfExportQuality: {}", inner),
        };
    }
}

impl SseDecode for crate::api::pdf_export::PdfExportStatus {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::api::pdf_export::PdfExportStatus::Running,
            1 => crate::api::pdf_export::PdfExportStatus::Complete,
            2 => crate::api::pdf_export::PdfExportStatus::Failed,
            _ => unreachable!("Invalid variant for PdfExportStatus: {}", inner),
        };
    }
}

impl SseDecode for crate::api::pdf_export::PdfExportUpdate {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_status = <crate::api::pdf_export::PdfExportStatus>::sse_decode(deserializer);
        let mut var_totalPageCount = <u32>::sse_decode(deserializer);
        let mut var_completedPageCount = <u32>::sse_decode(deserializer);
        let mut var_currentPage = <Option<u32>>::sse_decode(deserializer);
        let mut var_outputFiles = <Vec<String>>::sse_decode(deserializer);
        let mut var_error = <Option<crate::api::error::ApplicationError>>::sse_decode(deserializer);
        return crate::api::pdf_export::PdfExportUpdate {
            status: var_status,
            total_page_count: var_totalPageCount,
            completed_page_count: var_completedPageCount,
            current_page: var_currentPage,
            output_files: var_outputFiles,
            error: var_error,
        };
    }
}

impl SseDecode for crate::api::pdf_preview::PdfPageSize {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_widthPoints = <f64>::sse_decode(deserializer);
        let mut var_heightPoints = <f64>::sse_decode(deserializer);
        return crate::api::pdf_preview::PdfPageSize {
            width_points: var_widthPoints,
            height_points: var_heightPoints,
        };
    }
}

impl SseDecode for crate::api::pdf_preview::RenderPdfPageRequest {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_sourcePath = <String>::sse_decode(deserializer);
        let mut var_pageIndex = <u32>::sse_decode(deserializer);
        let mut var_targetWidth = <u32>::sse_decode(deserializer);
        let mut var_destinationPath = <Option<String>>::sse_decode(deserializer);
        return crate::api::pdf_preview::RenderPdfPageRequest {
            source_path: var_sourcePath,
            page_index: var_pageIndex,
            target_width: var_targetWidth,
            destination_path: var_destinationPath,
        };
    }
}

impl SseDecode for crate::api::pdf_preview::RenderPdfPageResult {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_outputPath = <String>::sse_decode(deserializer);
        let mut var_widthPixels = <u32>::sse_decode(deserializer);
        let mut var_heightPixels = <u32>::sse_decode(deserializer);
        return crate::api::pdf_preview::RenderPdfPageResult {
            output_path: var_outputPath,
            width_pixels: var_widthPixels,
            height_pixels: var_heightPixels,
        };
    }
}

impl SseDecode for u32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u32::<NativeEndian>().unwrap()
    }
}

impl SseDecode for u8 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap()
    }
}

impl SseDecode for () {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {}
}

fn pde_ffi_dispatcher_primary_impl(
    func_id: i32,
    port: flutter_rust_bridge::for_generated::MessagePort,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        1 => wire__crate__api__image_to_pdf__create_pdfs_from_images_impl(
            port,
            ptr,
            rust_vec_len,
            data_len,
        ),
        2 => wire__crate__api__pdf_export__export_pdf_batch_to_images_impl(
            port,
            ptr,
            rust_vec_len,
            data_len,
        ),
        3 => wire__crate__api__pdf_export__export_pdf_to_images_impl(
            port,
            ptr,
            rust_vec_len,
            data_len,
        ),
        4 => wire__crate__api__application__get_application_info_impl(
            port,
            ptr,
            rust_vec_len,
            data_len,
        ),
        5 => wire__crate__api__lifecycle__initialize_impl(port, ptr, rust_vec_len, data_len),
        6 => wire__crate__api__merge_pdf__merge_pdf_impl(port, ptr, rust_vec_len, data_len),
        7 => {
            wire__crate__api__pdf_preview__open_pdf_document_impl(port, ptr, rust_vec_len, data_len)
        }
        8 => wire__crate__api__pdf_preview__render_pdf_page_impl(port, ptr, rust_vec_len, data_len),
        _ => unreachable!(),
    }
}

fn pde_ffi_dispatcher_sync_impl(
    func_id: i32,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        _ => unreachable!(),
    }
}

// Section: rust2dart

// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::error::ApplicationError {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.code.into_into_dart().into_dart(),
            self.message.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::error::ApplicationError
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::error::ApplicationError>
    for crate::api::error::ApplicationError
{
    fn into_into_dart(self) -> crate::api::error::ApplicationError {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::error::ApplicationErrorCode {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            Self::SourceNotFound => 0.into_dart(),
            Self::SourceNotFile => 1.into_dart(),
            Self::SourceUnreadable => 2.into_dart(),
            Self::InvalidPdf => 3.into_dart(),
            Self::PageOutOfBounds => 4.into_dart(),
            Self::InvalidRequest => 5.into_dart(),
            Self::PdfRuntimeUnavailable => 6.into_dart(),
            Self::StructuralPdfRuntimeUnavailable => 7.into_dart(),
            Self::StructuralPdfRuntimeIncompatible => 8.into_dart(),
            Self::StructuralPdfLaunchFailed => 9.into_dart(),
            Self::PasswordRequired => 10.into_dart(),
            Self::StructuralPdfOperationFailed => 11.into_dart(),
            Self::StructuralPdfOutputValidationFailed => 12.into_dart(),
            Self::InvalidOutputDirectory => 13.into_dart(),
            Self::PermissionDenied => 14.into_dart(),
            Self::OutputNotWritable => 15.into_dart(),
            Self::OutputAlreadyExists => 16.into_dart(),
            Self::OutputWriteFailed => 17.into_dart(),
            Self::RenderingFailed => 18.into_dart(),
            Self::EncodingFailed => 19.into_dart(),
            Self::UnsupportedImageFormat => 20.into_dart(),
            Self::MalformedImage => 21.into_dart(),
            Self::ImageDecodeFailed => 22.into_dart(),
            Self::ImageOrientationFailed => 23.into_dart(),
            Self::DuplicateOutputName => 24.into_dart(),
            Self::PdfDocumentCreationFailed => 25.into_dart(),
            Self::PdfPageCreationFailed => 26.into_dart(),
            Self::ImagePlacementFailed => 27.into_dart(),
            Self::PdfSaveFailed => 28.into_dart(),
            Self::Internal => 29.into_dart(),
            _ => unreachable!(),
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::error::ApplicationErrorCode
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::error::ApplicationErrorCode>
    for crate::api::error::ApplicationErrorCode
{
    fn into_into_dart(self) -> crate::api::error::ApplicationErrorCode {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::application::ApplicationInfo {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.name.into_into_dart().into_dart(),
            self.version.into_into_dart().into_dart(),
            self.local_only.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::application::ApplicationInfo
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::application::ApplicationInfo>
    for crate::api::application::ApplicationInfo
{
    fn into_into_dart(self) -> crate::api::application::ApplicationInfo {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::image_to_pdf::CreateImagePdfRequest {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.source_paths.into_into_dart().into_dart(),
            self.destination_directory.into_into_dart().into_dart(),
            self.page_size.into_into_dart().into_dart(),
            self.orientation.into_into_dart().into_dart(),
            self.margin.into_into_dart().into_dart(),
            self.merge.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::image_to_pdf::CreateImagePdfRequest
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::image_to_pdf::CreateImagePdfRequest>
    for crate::api::image_to_pdf::CreateImagePdfRequest
{
    fn into_into_dart(self) -> crate::api::image_to_pdf::CreateImagePdfRequest {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::pdf_export::ExportPdfBatchRequest {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.source_paths.into_into_dart().into_dart(),
            self.destination_mode.into_into_dart().into_dart(),
            self.custom_destination_directory
                .into_into_dart()
                .into_dart(),
            self.quality.into_into_dart().into_dart(),
            self.format.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::pdf_export::ExportPdfBatchRequest
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::pdf_export::ExportPdfBatchRequest>
    for crate::api::pdf_export::ExportPdfBatchRequest
{
    fn into_into_dart(self) -> crate::api::pdf_export::ExportPdfBatchRequest {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::pdf_export::ExportPdfToImagesRequest {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.source_path.into_into_dart().into_dart(),
            self.destination_directory.into_into_dart().into_dart(),
            self.quality.into_into_dart().into_dart(),
            self.format.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::pdf_export::ExportPdfToImagesRequest
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::pdf_export::ExportPdfToImagesRequest>
    for crate::api::pdf_export::ExportPdfToImagesRequest
{
    fn into_into_dart(self) -> crate::api::pdf_export::ExportPdfToImagesRequest {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::image_to_pdf::ImagePdfMargin {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            Self::None => 0.into_dart(),
            Self::Small => 1.into_dart(),
            Self::Big => 2.into_dart(),
            _ => unreachable!(),
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::image_to_pdf::ImagePdfMargin
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::image_to_pdf::ImagePdfMargin>
    for crate::api::image_to_pdf::ImagePdfMargin
{
    fn into_into_dart(self) -> crate::api::image_to_pdf::ImagePdfMargin {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::image_to_pdf::ImagePdfOrientation {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            Self::Portrait => 0.into_dart(),
            Self::Landscape => 1.into_dart(),
            _ => unreachable!(),
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::image_to_pdf::ImagePdfOrientation
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::image_to_pdf::ImagePdfOrientation>
    for crate::api::image_to_pdf::ImagePdfOrientation
{
    fn into_into_dart(self) -> crate::api::image_to_pdf::ImagePdfOrientation {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::image_to_pdf::ImagePdfPageSize {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            Self::Fit => 0.into_dart(),
            Self::A4 => 1.into_dart(),
            Self::UsLetter => 2.into_dart(),
            _ => unreachable!(),
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::image_to_pdf::ImagePdfPageSize
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::image_to_pdf::ImagePdfPageSize>
    for crate::api::image_to_pdf::ImagePdfPageSize
{
    fn into_into_dart(self) -> crate::api::image_to_pdf::ImagePdfPageSize {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::image_to_pdf::ImagePdfStatus {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            Self::Running => 0.into_dart(),
            Self::Complete => 1.into_dart(),
            Self::Failed => 2.into_dart(),
            _ => unreachable!(),
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::image_to_pdf::ImagePdfStatus
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::image_to_pdf::ImagePdfStatus>
    for crate::api::image_to_pdf::ImagePdfStatus
{
    fn into_into_dart(self) -> crate::api::image_to_pdf::ImagePdfStatus {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::image_to_pdf::ImagePdfUpdate {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.status.into_into_dart().into_dart(),
            self.total_image_count.into_into_dart().into_dart(),
            self.completed_image_count.into_into_dart().into_dart(),
            self.current_image.into_into_dart().into_dart(),
            self.output_files.into_into_dart().into_dart(),
            self.error.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::image_to_pdf::ImagePdfUpdate
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::image_to_pdf::ImagePdfUpdate>
    for crate::api::image_to_pdf::ImagePdfUpdate
{
    fn into_into_dart(self) -> crate::api::image_to_pdf::ImagePdfUpdate {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::merge_pdf::MergePdfRequest {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.source_paths.into_into_dart().into_dart(),
            self.destination_directory.into_into_dart().into_dart(),
            self.output_name.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::merge_pdf::MergePdfRequest
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::merge_pdf::MergePdfRequest>
    for crate::api::merge_pdf::MergePdfRequest
{
    fn into_into_dart(self) -> crate::api::merge_pdf::MergePdfRequest {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::merge_pdf::MergePdfStage {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            Self::Preparing => 0.into_dart(),
            Self::Merging => 1.into_dart(),
            Self::Validating => 2.into_dart(),
            Self::Publishing => 3.into_dart(),
            Self::Completed => 4.into_dart(),
            _ => unreachable!(),
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::merge_pdf::MergePdfStage
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::merge_pdf::MergePdfStage>
    for crate::api::merge_pdf::MergePdfStage
{
    fn into_into_dart(self) -> crate::api::merge_pdf::MergePdfStage {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::merge_pdf::MergePdfStatus {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            Self::Running => 0.into_dart(),
            Self::Complete => 1.into_dart(),
            Self::Failed => 2.into_dart(),
            _ => unreachable!(),
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::merge_pdf::MergePdfStatus
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::merge_pdf::MergePdfStatus>
    for crate::api::merge_pdf::MergePdfStatus
{
    fn into_into_dart(self) -> crate::api::merge_pdf::MergePdfStatus {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::merge_pdf::MergePdfUpdate {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.status.into_into_dart().into_dart(),
            self.stage.into_into_dart().into_dart(),
            self.input_count.into_into_dart().into_dart(),
            self.total_page_count.into_into_dart().into_dart(),
            self.output_path.into_into_dart().into_dart(),
            self.warning_input_count.into_into_dart().into_dart(),
            self.has_warnings.into_into_dart().into_dart(),
            self.failed_input_index.into_into_dart().into_dart(),
            self.failed_input_path.into_into_dart().into_dart(),
            self.error.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::merge_pdf::MergePdfUpdate
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::merge_pdf::MergePdfUpdate>
    for crate::api::merge_pdf::MergePdfUpdate
{
    fn into_into_dart(self) -> crate::api::merge_pdf::MergePdfUpdate {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::pdf_export::PdfBatchDestinationMode {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            Self::NextToSourceFiles => 0.into_dart(),
            Self::CustomFolder => 1.into_dart(),
            _ => unreachable!(),
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::pdf_export::PdfBatchDestinationMode
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::pdf_export::PdfBatchDestinationMode>
    for crate::api::pdf_export::PdfBatchDestinationMode
{
    fn into_into_dart(self) -> crate::api::pdf_export::PdfBatchDestinationMode {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::pdf_export::PdfBatchDocumentResult {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.source_path.into_into_dart().into_dart(),
            self.display_name.into_into_dart().into_dart(),
            self.total_page_count.into_into_dart().into_dart(),
            self.completed_page_count.into_into_dart().into_dart(),
            self.output_files.into_into_dart().into_dart(),
            self.error.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::pdf_export::PdfBatchDocumentResult
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::pdf_export::PdfBatchDocumentResult>
    for crate::api::pdf_export::PdfBatchDocumentResult
{
    fn into_into_dart(self) -> crate::api::pdf_export::PdfBatchDocumentResult {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::pdf_export::PdfBatchExportStatus {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            Self::Running => 0.into_dart(),
            Self::Complete => 1.into_dart(),
            Self::CompleteWithErrors => 2.into_dart(),
            Self::Failed => 3.into_dart(),
            _ => unreachable!(),
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::pdf_export::PdfBatchExportStatus
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::pdf_export::PdfBatchExportStatus>
    for crate::api::pdf_export::PdfBatchExportStatus
{
    fn into_into_dart(self) -> crate::api::pdf_export::PdfBatchExportStatus {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::pdf_export::PdfBatchExportUpdate {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.status.into_into_dart().into_dart(),
            self.total_document_count.into_into_dart().into_dart(),
            self.completed_document_count.into_into_dart().into_dart(),
            self.succeeded_document_count.into_into_dart().into_dart(),
            self.failed_document_count.into_into_dart().into_dart(),
            self.current_document_index.into_into_dart().into_dart(),
            self.current_document_filename.into_into_dart().into_dart(),
            self.total_page_count.into_into_dart().into_dart(),
            self.completed_page_count.into_into_dart().into_dart(),
            self.current_page.into_into_dart().into_dart(),
            self.documents.into_into_dart().into_dart(),
            self.error.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::pdf_export::PdfBatchExportUpdate
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::pdf_export::PdfBatchExportUpdate>
    for crate::api::pdf_export::PdfBatchExportUpdate
{
    fn into_into_dart(self) -> crate::api::pdf_export::PdfBatchExportUpdate {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::pdf_preview::PdfDocumentInfo {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.page_count.into_into_dart().into_dart(),
            self.first_page_size.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::pdf_preview::PdfDocumentInfo
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::pdf_preview::PdfDocumentInfo>
    for crate::api::pdf_preview::PdfDocumentInfo
{
    fn into_into_dart(self) -> crate::api::pdf_preview::PdfDocumentInfo {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::pdf_export::PdfExportFormat {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            Self::Png => 0.into_dart(),
            Self::Jpg => 1.into_dart(),
            _ => unreachable!(),
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::pdf_export::PdfExportFormat
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::pdf_export::PdfExportFormat>
    for crate::api::pdf_export::PdfExportFormat
{
    fn into_into_dart(self) -> crate::api::pdf_export::PdfExportFormat {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::pdf_export::PdfExportQuality {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            Self::Standard => 0.into_dart(),
            Self::HighQuality => 1.into_dart(),
            _ => unreachable!(),
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::pdf_export::PdfExportQuality
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::pdf_export::PdfExportQuality>
    for crate::api::pdf_export::PdfExportQuality
{
    fn into_into_dart(self) -> crate::api::pdf_export::PdfExportQuality {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::pdf_export::PdfExportStatus {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            Self::Running => 0.into_dart(),
            Self::Complete => 1.into_dart(),
            Self::Failed => 2.into_dart(),
            _ => unreachable!(),
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::pdf_export::PdfExportStatus
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::pdf_export::PdfExportStatus>
    for crate::api::pdf_export::PdfExportStatus
{
    fn into_into_dart(self) -> crate::api::pdf_export::PdfExportStatus {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::pdf_export::PdfExportUpdate {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.status.into_into_dart().into_dart(),
            self.total_page_count.into_into_dart().into_dart(),
            self.completed_page_count.into_into_dart().into_dart(),
            self.current_page.into_into_dart().into_dart(),
            self.output_files.into_into_dart().into_dart(),
            self.error.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::pdf_export::PdfExportUpdate
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::pdf_export::PdfExportUpdate>
    for crate::api::pdf_export::PdfExportUpdate
{
    fn into_into_dart(self) -> crate::api::pdf_export::PdfExportUpdate {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::pdf_preview::PdfPageSize {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.width_points.into_into_dart().into_dart(),
            self.height_points.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::pdf_preview::PdfPageSize
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::pdf_preview::PdfPageSize>
    for crate::api::pdf_preview::PdfPageSize
{
    fn into_into_dart(self) -> crate::api::pdf_preview::PdfPageSize {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::pdf_preview::RenderPdfPageRequest {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.source_path.into_into_dart().into_dart(),
            self.page_index.into_into_dart().into_dart(),
            self.target_width.into_into_dart().into_dart(),
            self.destination_path.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::pdf_preview::RenderPdfPageRequest
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::pdf_preview::RenderPdfPageRequest>
    for crate::api::pdf_preview::RenderPdfPageRequest
{
    fn into_into_dart(self) -> crate::api::pdf_preview::RenderPdfPageRequest {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::pdf_preview::RenderPdfPageResult {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.output_path.into_into_dart().into_dart(),
            self.width_pixels.into_into_dart().into_dart(),
            self.height_pixels.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::pdf_preview::RenderPdfPageResult
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::pdf_preview::RenderPdfPageResult>
    for crate::api::pdf_preview::RenderPdfPageResult
{
    fn into_into_dart(self) -> crate::api::pdf_preview::RenderPdfPageResult {
        self
    }
}

impl SseEncode for flutter_rust_bridge::for_generated::anyhow::Error {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(format!("{:?}", self), serializer);
    }
}

impl SseEncode
    for StreamSink<
        crate::api::image_to_pdf::ImagePdfUpdate,
        flutter_rust_bridge::for_generated::SseCodec,
    >
{
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        unimplemented!("")
    }
}

impl SseEncode
    for StreamSink<
        crate::api::merge_pdf::MergePdfUpdate,
        flutter_rust_bridge::for_generated::SseCodec,
    >
{
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        unimplemented!("")
    }
}

impl SseEncode
    for StreamSink<
        crate::api::pdf_export::PdfBatchExportUpdate,
        flutter_rust_bridge::for_generated::SseCodec,
    >
{
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        unimplemented!("")
    }
}

impl SseEncode
    for StreamSink<
        crate::api::pdf_export::PdfExportUpdate,
        flutter_rust_bridge::for_generated::SseCodec,
    >
{
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        unimplemented!("")
    }
}

impl SseEncode for String {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Vec<u8>>::sse_encode(self.into_bytes(), serializer);
    }
}

impl SseEncode for crate::api::error::ApplicationError {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <crate::api::error::ApplicationErrorCode>::sse_encode(self.code, serializer);
        <String>::sse_encode(self.message, serializer);
    }
}

impl SseEncode for crate::api::error::ApplicationErrorCode {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(
            match self {
                crate::api::error::ApplicationErrorCode::SourceNotFound => 0,
                crate::api::error::ApplicationErrorCode::SourceNotFile => 1,
                crate::api::error::ApplicationErrorCode::SourceUnreadable => 2,
                crate::api::error::ApplicationErrorCode::InvalidPdf => 3,
                crate::api::error::ApplicationErrorCode::PageOutOfBounds => 4,
                crate::api::error::ApplicationErrorCode::InvalidRequest => 5,
                crate::api::error::ApplicationErrorCode::PdfRuntimeUnavailable => 6,
                crate::api::error::ApplicationErrorCode::StructuralPdfRuntimeUnavailable => 7,
                crate::api::error::ApplicationErrorCode::StructuralPdfRuntimeIncompatible => 8,
                crate::api::error::ApplicationErrorCode::StructuralPdfLaunchFailed => 9,
                crate::api::error::ApplicationErrorCode::PasswordRequired => 10,
                crate::api::error::ApplicationErrorCode::StructuralPdfOperationFailed => 11,
                crate::api::error::ApplicationErrorCode::StructuralPdfOutputValidationFailed => 12,
                crate::api::error::ApplicationErrorCode::InvalidOutputDirectory => 13,
                crate::api::error::ApplicationErrorCode::PermissionDenied => 14,
                crate::api::error::ApplicationErrorCode::OutputNotWritable => 15,
                crate::api::error::ApplicationErrorCode::OutputAlreadyExists => 16,
                crate::api::error::ApplicationErrorCode::OutputWriteFailed => 17,
                crate::api::error::ApplicationErrorCode::RenderingFailed => 18,
                crate::api::error::ApplicationErrorCode::EncodingFailed => 19,
                crate::api::error::ApplicationErrorCode::UnsupportedImageFormat => 20,
                crate::api::error::ApplicationErrorCode::MalformedImage => 21,
                crate::api::error::ApplicationErrorCode::ImageDecodeFailed => 22,
                crate::api::error::ApplicationErrorCode::ImageOrientationFailed => 23,
                crate::api::error::ApplicationErrorCode::DuplicateOutputName => 24,
                crate::api::error::ApplicationErrorCode::PdfDocumentCreationFailed => 25,
                crate::api::error::ApplicationErrorCode::PdfPageCreationFailed => 26,
                crate::api::error::ApplicationErrorCode::ImagePlacementFailed => 27,
                crate::api::error::ApplicationErrorCode::PdfSaveFailed => 28,
                crate::api::error::ApplicationErrorCode::Internal => 29,
                _ => {
                    unimplemented!("");
                }
            },
            serializer,
        );
    }
}

impl SseEncode for crate::api::application::ApplicationInfo {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.name, serializer);
        <String>::sse_encode(self.version, serializer);
        <bool>::sse_encode(self.local_only, serializer);
    }
}

impl SseEncode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self as _).unwrap();
    }
}

impl SseEncode for crate::api::image_to_pdf::CreateImagePdfRequest {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Vec<String>>::sse_encode(self.source_paths, serializer);
        <String>::sse_encode(self.destination_directory, serializer);
        <crate::api::image_to_pdf::ImagePdfPageSize>::sse_encode(self.page_size, serializer);
        <crate::api::image_to_pdf::ImagePdfOrientation>::sse_encode(self.orientation, serializer);
        <crate::api::image_to_pdf::ImagePdfMargin>::sse_encode(self.margin, serializer);
        <bool>::sse_encode(self.merge, serializer);
    }
}

impl SseEncode for crate::api::pdf_export::ExportPdfBatchRequest {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Vec<String>>::sse_encode(self.source_paths, serializer);
        <crate::api::pdf_export::PdfBatchDestinationMode>::sse_encode(
            self.destination_mode,
            serializer,
        );
        <Option<String>>::sse_encode(self.custom_destination_directory, serializer);
        <crate::api::pdf_export::PdfExportQuality>::sse_encode(self.quality, serializer);
        <crate::api::pdf_export::PdfExportFormat>::sse_encode(self.format, serializer);
    }
}

impl SseEncode for crate::api::pdf_export::ExportPdfToImagesRequest {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.source_path, serializer);
        <String>::sse_encode(self.destination_directory, serializer);
        <crate::api::pdf_export::PdfExportQuality>::sse_encode(self.quality, serializer);
        <crate::api::pdf_export::PdfExportFormat>::sse_encode(self.format, serializer);
    }
}

impl SseEncode for f64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_f64::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_i32::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for crate::api::image_to_pdf::ImagePdfMargin {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(
            match self {
                crate::api::image_to_pdf::ImagePdfMargin::None => 0,
                crate::api::image_to_pdf::ImagePdfMargin::Small => 1,
                crate::api::image_to_pdf::ImagePdfMargin::Big => 2,
                _ => {
                    unimplemented!("");
                }
            },
            serializer,
        );
    }
}

impl SseEncode for crate::api::image_to_pdf::ImagePdfOrientation {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(
            match self {
                crate::api::image_to_pdf::ImagePdfOrientation::Portrait => 0,
                crate::api::image_to_pdf::ImagePdfOrientation::Landscape => 1,
                _ => {
                    unimplemented!("");
                }
            },
            serializer,
        );
    }
}

impl SseEncode for crate::api::image_to_pdf::ImagePdfPageSize {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(
            match self {
                crate::api::image_to_pdf::ImagePdfPageSize::Fit => 0,
                crate::api::image_to_pdf::ImagePdfPageSize::A4 => 1,
                crate::api::image_to_pdf::ImagePdfPageSize::UsLetter => 2,
                _ => {
                    unimplemented!("");
                }
            },
            serializer,
        );
    }
}

impl SseEncode for crate::api::image_to_pdf::ImagePdfStatus {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(
            match self {
                crate::api::image_to_pdf::ImagePdfStatus::Running => 0,
                crate::api::image_to_pdf::ImagePdfStatus::Complete => 1,
                crate::api::image_to_pdf::ImagePdfStatus::Failed => 2,
                _ => {
                    unimplemented!("");
                }
            },
            serializer,
        );
    }
}

impl SseEncode for crate::api::image_to_pdf::ImagePdfUpdate {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <crate::api::image_to_pdf::ImagePdfStatus>::sse_encode(self.status, serializer);
        <u32>::sse_encode(self.total_image_count, serializer);
        <u32>::sse_encode(self.completed_image_count, serializer);
        <Option<u32>>::sse_encode(self.current_image, serializer);
        <Vec<String>>::sse_encode(self.output_files, serializer);
        <Option<crate::api::error::ApplicationError>>::sse_encode(self.error, serializer);
    }
}

impl SseEncode for Vec<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <String>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::api::pdf_export::PdfBatchDocumentResult> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::pdf_export::PdfBatchDocumentResult>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <u8>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for crate::api::merge_pdf::MergePdfRequest {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Vec<String>>::sse_encode(self.source_paths, serializer);
        <String>::sse_encode(self.destination_directory, serializer);
        <String>::sse_encode(self.output_name, serializer);
    }
}

impl SseEncode for crate::api::merge_pdf::MergePdfStage {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(
            match self {
                crate::api::merge_pdf::MergePdfStage::Preparing => 0,
                crate::api::merge_pdf::MergePdfStage::Merging => 1,
                crate::api::merge_pdf::MergePdfStage::Validating => 2,
                crate::api::merge_pdf::MergePdfStage::Publishing => 3,
                crate::api::merge_pdf::MergePdfStage::Completed => 4,
                _ => {
                    unimplemented!("");
                }
            },
            serializer,
        );
    }
}

impl SseEncode for crate::api::merge_pdf::MergePdfStatus {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(
            match self {
                crate::api::merge_pdf::MergePdfStatus::Running => 0,
                crate::api::merge_pdf::MergePdfStatus::Complete => 1,
                crate::api::merge_pdf::MergePdfStatus::Failed => 2,
                _ => {
                    unimplemented!("");
                }
            },
            serializer,
        );
    }
}

impl SseEncode for crate::api::merge_pdf::MergePdfUpdate {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <crate::api::merge_pdf::MergePdfStatus>::sse_encode(self.status, serializer);
        <crate::api::merge_pdf::MergePdfStage>::sse_encode(self.stage, serializer);
        <u32>::sse_encode(self.input_count, serializer);
        <u32>::sse_encode(self.total_page_count, serializer);
        <Option<String>>::sse_encode(self.output_path, serializer);
        <u32>::sse_encode(self.warning_input_count, serializer);
        <bool>::sse_encode(self.has_warnings, serializer);
        <Option<u32>>::sse_encode(self.failed_input_index, serializer);
        <Option<String>>::sse_encode(self.failed_input_path, serializer);
        <Option<crate::api::error::ApplicationError>>::sse_encode(self.error, serializer);
    }
}

impl SseEncode for Option<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <String>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<crate::api::error::ApplicationError> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <crate::api::error::ApplicationError>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<crate::api::pdf_preview::PdfPageSize> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <crate::api::pdf_preview::PdfPageSize>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<u32> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <u32>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for crate::api::pdf_export::PdfBatchDestinationMode {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(
            match self {
                crate::api::pdf_export::PdfBatchDestinationMode::NextToSourceFiles => 0,
                crate::api::pdf_export::PdfBatchDestinationMode::CustomFolder => 1,
                _ => {
                    unimplemented!("");
                }
            },
            serializer,
        );
    }
}

impl SseEncode for crate::api::pdf_export::PdfBatchDocumentResult {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.source_path, serializer);
        <String>::sse_encode(self.display_name, serializer);
        <u32>::sse_encode(self.total_page_count, serializer);
        <u32>::sse_encode(self.completed_page_count, serializer);
        <Vec<String>>::sse_encode(self.output_files, serializer);
        <Option<crate::api::error::ApplicationError>>::sse_encode(self.error, serializer);
    }
}

impl SseEncode for crate::api::pdf_export::PdfBatchExportStatus {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(
            match self {
                crate::api::pdf_export::PdfBatchExportStatus::Running => 0,
                crate::api::pdf_export::PdfBatchExportStatus::Complete => 1,
                crate::api::pdf_export::PdfBatchExportStatus::CompleteWithErrors => 2,
                crate::api::pdf_export::PdfBatchExportStatus::Failed => 3,
                _ => {
                    unimplemented!("");
                }
            },
            serializer,
        );
    }
}

impl SseEncode for crate::api::pdf_export::PdfBatchExportUpdate {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <crate::api::pdf_export::PdfBatchExportStatus>::sse_encode(self.status, serializer);
        <u32>::sse_encode(self.total_document_count, serializer);
        <u32>::sse_encode(self.completed_document_count, serializer);
        <u32>::sse_encode(self.succeeded_document_count, serializer);
        <u32>::sse_encode(self.failed_document_count, serializer);
        <Option<u32>>::sse_encode(self.current_document_index, serializer);
        <Option<String>>::sse_encode(self.current_document_filename, serializer);
        <u32>::sse_encode(self.total_page_count, serializer);
        <u32>::sse_encode(self.completed_page_count, serializer);
        <Option<u32>>::sse_encode(self.current_page, serializer);
        <Vec<crate::api::pdf_export::PdfBatchDocumentResult>>::sse_encode(
            self.documents,
            serializer,
        );
        <Option<crate::api::error::ApplicationError>>::sse_encode(self.error, serializer);
    }
}

impl SseEncode for crate::api::pdf_preview::PdfDocumentInfo {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <u32>::sse_encode(self.page_count, serializer);
        <Option<crate::api::pdf_preview::PdfPageSize>>::sse_encode(
            self.first_page_size,
            serializer,
        );
    }
}

impl SseEncode for crate::api::pdf_export::PdfExportFormat {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(
            match self {
                crate::api::pdf_export::PdfExportFormat::Png => 0,
                crate::api::pdf_export::PdfExportFormat::Jpg => 1,
                _ => {
                    unimplemented!("");
                }
            },
            serializer,
        );
    }
}

impl SseEncode for crate::api::pdf_export::PdfExportQuality {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(
            match self {
                crate::api::pdf_export::PdfExportQuality::Standard => 0,
                crate::api::pdf_export::PdfExportQuality::HighQuality => 1,
                _ => {
                    unimplemented!("");
                }
            },
            serializer,
        );
    }
}

impl SseEncode for crate::api::pdf_export::PdfExportStatus {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(
            match self {
                crate::api::pdf_export::PdfExportStatus::Running => 0,
                crate::api::pdf_export::PdfExportStatus::Complete => 1,
                crate::api::pdf_export::PdfExportStatus::Failed => 2,
                _ => {
                    unimplemented!("");
                }
            },
            serializer,
        );
    }
}

impl SseEncode for crate::api::pdf_export::PdfExportUpdate {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <crate::api::pdf_export::PdfExportStatus>::sse_encode(self.status, serializer);
        <u32>::sse_encode(self.total_page_count, serializer);
        <u32>::sse_encode(self.completed_page_count, serializer);
        <Option<u32>>::sse_encode(self.current_page, serializer);
        <Vec<String>>::sse_encode(self.output_files, serializer);
        <Option<crate::api::error::ApplicationError>>::sse_encode(self.error, serializer);
    }
}

impl SseEncode for crate::api::pdf_preview::PdfPageSize {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <f64>::sse_encode(self.width_points, serializer);
        <f64>::sse_encode(self.height_points, serializer);
    }
}

impl SseEncode for crate::api::pdf_preview::RenderPdfPageRequest {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.source_path, serializer);
        <u32>::sse_encode(self.page_index, serializer);
        <u32>::sse_encode(self.target_width, serializer);
        <Option<String>>::sse_encode(self.destination_path, serializer);
    }
}

impl SseEncode for crate::api::pdf_preview::RenderPdfPageResult {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.output_path, serializer);
        <u32>::sse_encode(self.width_pixels, serializer);
        <u32>::sse_encode(self.height_pixels, serializer);
    }
}

impl SseEncode for u32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u32::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for u8 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self).unwrap();
    }
}

impl SseEncode for () {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {}
}

#[cfg(not(target_family = "wasm"))]
mod io {
    // This file is automatically generated, so please do not edit it.
    // @generated by `flutter_rust_bridge`@ 2.13.0.

    // Section: imports

    use super::*;
    use flutter_rust_bridge::for_generated::byteorder::{
        NativeEndian, ReadBytesExt, WriteBytesExt,
    };
    use flutter_rust_bridge::for_generated::{Lifetimeable, Lockable, transform_result_dco};
    use flutter_rust_bridge::{Handler, IntoIntoDart};

    // Section: boilerplate

    flutter_rust_bridge::frb_generated_boilerplate_io!();
}
#[cfg(not(target_family = "wasm"))]
pub use io::*;

/// cbindgen:ignore
#[cfg(target_family = "wasm")]
mod web {
    // This file is automatically generated, so please do not edit it.
    // @generated by `flutter_rust_bridge`@ 2.13.0.

    // Section: imports

    use super::*;
    use flutter_rust_bridge::for_generated::byteorder::{
        NativeEndian, ReadBytesExt, WriteBytesExt,
    };
    use flutter_rust_bridge::for_generated::wasm_bindgen;
    use flutter_rust_bridge::for_generated::wasm_bindgen::prelude::*;
    use flutter_rust_bridge::for_generated::{Lifetimeable, Lockable, transform_result_dco};
    use flutter_rust_bridge::{Handler, IntoIntoDart};

    // Section: boilerplate

    flutter_rust_bridge::frb_generated_boilerplate_web!();
}
#[cfg(target_family = "wasm")]
pub use web::*;
