// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'error.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `display_object`, `edit_error`, `geometry_error`, `lock`, `map_box`, `map_point`, `validate_edit_layout`, `viewport_point`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`

Future<EditorSession> openEditorSession({required String sourcePath}) => RustLib
    .instance
    .api
    .crateApiEditorOpenEditorSession(sourcePath: sourcePath);

double stepEditorZoom({required double scale, required bool increase}) =>
    RustLib.instance.api.crateApiEditorStepEditorZoom(
      scale: scale,
      increase: increase,
    );

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<EditorEdits>>
abstract class EditorEdits implements RustOpaqueInterface {
  void addPrototype({required int pageIndex});

  EditorObjectGesture? beginGesture({
    required EditorLayoutBinding layout,
    required EditorPoint point,
  });

  void clearSelection();

  bool deleteSelected();

  bool finishGesture({
    required EditorObjectGesture gesture,
    required EditorPoint point,
  });

  List<EditorObjectDisplay> projectPage({
    required EditorLayoutBinding layout,
    required int pageIndex,
  });

  bool redo();

  EditorEditSnapshot snapshot();

  bool undo();
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<EditorLayoutBinding>>
abstract class EditorLayoutBinding implements RustOpaqueInterface {
  EditorPoint anchoredScroll({
    required EditorLayoutBinding previous,
    required EditorPoint scroll,
    required EditorPoint viewport,
  });

  EditorHit? hitTest({required EditorPoint point, required EditorPoint scroll});

  EditorRasterSize renderSize({
    required int pageIndex,
    required double density,
  });

  Uint32List visiblePages({
    required double top,
    required double height,
    required double overscan,
  });
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<EditorObjectGesture>>
abstract class EditorObjectGesture implements RustOpaqueInterface {
  int pageIndex();

  EditorObjectDisplay preview({required EditorPoint point});
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<EditorPageTransform>>
abstract class EditorPageTransform implements RustOpaqueInterface {
  EditorPoint pdfToDocument({required EditorPoint point});
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<EditorSession>>
abstract class EditorSession implements RustOpaqueInterface {
  EditorEdits createEdits();

  BigInt identity();

  /// Pure geometry; native rendering remains asynchronous on the worker pool.
  EditorDocumentLayout layout({
    required double workspaceWidth,
    required double scale,
    required bool fitWidth,
  });

  int pageCount();

  Future<EditorRaster> render({
    required int pageIndex,
    required EditorRasterSize size,
  });
}

class EditorDocumentLayout {
  final EditorLayoutBinding binding;
  final List<EditorPageLayout> pages;
  final double width;
  final double height;
  final double scale;

  const EditorDocumentLayout({
    required this.binding,
    required this.pages,
    required this.width,
    required this.height,
    required this.scale,
  });

  @override
  int get hashCode =>
      binding.hashCode ^
      pages.hashCode ^
      width.hashCode ^
      height.hashCode ^
      scale.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EditorDocumentLayout &&
          runtimeType == other.runtimeType &&
          binding == other.binding &&
          pages == other.pages &&
          width == other.width &&
          height == other.height &&
          scale == other.scale;
}

class EditorEditSnapshot {
  final BigInt sessionId;
  final List<EditorObject> objects;
  final BigInt? selected;
  final int undoCount;
  final int redoCount;

  const EditorEditSnapshot({
    required this.sessionId,
    required this.objects,
    this.selected,
    required this.undoCount,
    required this.redoCount,
  });

  @override
  int get hashCode =>
      sessionId.hashCode ^
      objects.hashCode ^
      selected.hashCode ^
      undoCount.hashCode ^
      redoCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EditorEditSnapshot &&
          runtimeType == other.runtimeType &&
          sessionId == other.sessionId &&
          objects == other.objects &&
          selected == other.selected &&
          undoCount == other.undoCount &&
          redoCount == other.redoCount;
}

class EditorHit {
  final int pageIndex;
  final EditorPoint pdfPoint;
  final EditorPoint pageLocalPoint;

  const EditorHit({
    required this.pageIndex,
    required this.pdfPoint,
    required this.pageLocalPoint,
  });

  @override
  int get hashCode =>
      pageIndex.hashCode ^ pdfPoint.hashCode ^ pageLocalPoint.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EditorHit &&
          runtimeType == other.runtimeType &&
          pageIndex == other.pageIndex &&
          pdfPoint == other.pdfPoint &&
          pageLocalPoint == other.pageLocalPoint;
}

class EditorObject {
  final BigInt id;
  final int pageIndex;
  final EditorObjectKind kind;
  final EditorPageBox rectangle;

  const EditorObject({
    required this.id,
    required this.pageIndex,
    required this.kind,
    required this.rectangle,
  });

  @override
  int get hashCode =>
      id.hashCode ^ pageIndex.hashCode ^ kind.hashCode ^ rectangle.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EditorObject &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          pageIndex == other.pageIndex &&
          kind == other.kind &&
          rectangle == other.rectangle;
}

class EditorObjectDisplay {
  final BigInt id;

  /// Document-surface logical rectangle, projected by the authoritative transform.
  final EditorRect rect;
  final bool selected;

  /// Eight display handle centers in clockwise order from top-left.
  final List<EditorPoint> handles;

  const EditorObjectDisplay({
    required this.id,
    required this.rect,
    required this.selected,
    required this.handles,
  });

  @override
  int get hashCode =>
      id.hashCode ^ rect.hashCode ^ selected.hashCode ^ handles.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EditorObjectDisplay &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          rect == other.rect &&
          selected == other.selected &&
          handles == other.handles;
}

enum EditorObjectKind { prototypeRectangle }

class EditorPageBox {
  final double left;
  final double bottom;
  final double right;
  final double top;

  const EditorPageBox({
    required this.left,
    required this.bottom,
    required this.right,
    required this.top,
  });

  @override
  int get hashCode =>
      left.hashCode ^ bottom.hashCode ^ right.hashCode ^ top.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EditorPageBox &&
          runtimeType == other.runtimeType &&
          left == other.left &&
          bottom == other.bottom &&
          right == other.right &&
          top == other.top;
}

class EditorPageGeometry {
  final EditorPageBox visibleBox;
  final EditorPageBox? declaredMediaBox;
  final EditorPageBox? declaredCropBox;
  final EditorPageRotation rotation;

  const EditorPageGeometry({
    required this.visibleBox,
    this.declaredMediaBox,
    this.declaredCropBox,
    required this.rotation,
  });

  @override
  int get hashCode =>
      visibleBox.hashCode ^
      declaredMediaBox.hashCode ^
      declaredCropBox.hashCode ^
      rotation.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EditorPageGeometry &&
          runtimeType == other.runtimeType &&
          visibleBox == other.visibleBox &&
          declaredMediaBox == other.declaredMediaBox &&
          declaredCropBox == other.declaredCropBox &&
          rotation == other.rotation;
}

class EditorPageLayout {
  final int pageIndex;
  final EditorRect rect;
  final double scale;
  final EditorPageGeometry geometry;
  final EditorPageTransform transform;

  const EditorPageLayout({
    required this.pageIndex,
    required this.rect,
    required this.scale,
    required this.geometry,
    required this.transform,
  });

  @override
  int get hashCode =>
      pageIndex.hashCode ^
      rect.hashCode ^
      scale.hashCode ^
      geometry.hashCode ^
      transform.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EditorPageLayout &&
          runtimeType == other.runtimeType &&
          pageIndex == other.pageIndex &&
          rect == other.rect &&
          scale == other.scale &&
          geometry == other.geometry &&
          transform == other.transform;
}

enum EditorPageRotation { none, clockwise90, halfTurn, clockwise270 }

class EditorPoint {
  final double x;
  final double y;

  const EditorPoint({required this.x, required this.y});

  @override
  int get hashCode => x.hashCode ^ y.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EditorPoint &&
          runtimeType == other.runtimeType &&
          x == other.x &&
          y == other.y;
}

class EditorRaster {
  final Uint8List png;
  final int width;
  final int height;

  const EditorRaster({
    required this.png,
    required this.width,
    required this.height,
  });

  @override
  int get hashCode => png.hashCode ^ width.hashCode ^ height.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EditorRaster &&
          runtimeType == other.runtimeType &&
          png == other.png &&
          width == other.width &&
          height == other.height;
}

class EditorRasterSize {
  final int width;
  final int height;

  const EditorRasterSize({required this.width, required this.height});

  @override
  int get hashCode => width.hashCode ^ height.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EditorRasterSize &&
          runtimeType == other.runtimeType &&
          width == other.width &&
          height == other.height;
}

class EditorRect {
  final double left;
  final double top;
  final double width;
  final double height;

  const EditorRect({
    required this.left,
    required this.top,
    required this.width,
    required this.height,
  });

  @override
  int get hashCode =>
      left.hashCode ^ top.hashCode ^ width.hashCode ^ height.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EditorRect &&
          runtimeType == other.runtimeType &&
          left == other.left &&
          top == other.top &&
          width == other.width &&
          height == other.height;
}
