// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'application.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `paths_to_strings`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

/// Creates PDFs sequentially on flutter_rust_bridge's worker pool and streams progress.
Stream<ImagePdfUpdate> createPdfsFromImages({
  required CreateImagePdfRequest request,
}) => RustLib.instance.api.crateApiImageToPdfCreatePdfsFromImages(
  request: request,
);

class CreateImagePdfRequest {
  final List<String> sourcePaths;
  final String destinationDirectory;
  final ImagePdfPageSize pageSize;
  final ImagePdfOrientation orientation;
  final ImagePdfMargin margin;
  final bool merge;

  const CreateImagePdfRequest({
    required this.sourcePaths,
    required this.destinationDirectory,
    required this.pageSize,
    required this.orientation,
    required this.margin,
    required this.merge,
  });

  @override
  int get hashCode =>
      sourcePaths.hashCode ^
      destinationDirectory.hashCode ^
      pageSize.hashCode ^
      orientation.hashCode ^
      margin.hashCode ^
      merge.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CreateImagePdfRequest &&
          runtimeType == other.runtimeType &&
          sourcePaths == other.sourcePaths &&
          destinationDirectory == other.destinationDirectory &&
          pageSize == other.pageSize &&
          orientation == other.orientation &&
          margin == other.margin &&
          merge == other.merge;
}

enum ImagePdfMargin { none, small, big }

enum ImagePdfOrientation { portrait, landscape }

enum ImagePdfPageSize { fit, a4, usLetter }

enum ImagePdfStatus { running, complete, failed }

class ImagePdfUpdate {
  final ImagePdfStatus status;
  final int totalImageCount;
  final int completedImageCount;
  final int? currentImage;
  final List<String> outputFiles;
  final ApplicationError? error;

  const ImagePdfUpdate({
    required this.status,
    required this.totalImageCount,
    required this.completedImageCount,
    this.currentImage,
    required this.outputFiles,
    this.error,
  });

  @override
  int get hashCode =>
      status.hashCode ^
      totalImageCount.hashCode ^
      completedImageCount.hashCode ^
      currentImage.hashCode ^
      outputFiles.hashCode ^
      error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ImagePdfUpdate &&
          runtimeType == other.runtimeType &&
          status == other.status &&
          totalImageCount == other.totalImageCount &&
          completedImageCount == other.completedImageCount &&
          currentImage == other.currentImage &&
          outputFiles == other.outputFiles &&
          error == other.error;
}
