// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'error.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `from`

/// Merges PDFs on flutter_rust_bridge's worker pool and streams real job stages.
Stream<MergePdfUpdate> mergePdf({required MergePdfRequest request}) =>
    RustLib.instance.api.crateApiMergePdfMergePdf(request: request);

class MergePdfRequest {
  final List<String> sourcePaths;
  final String destinationDirectory;
  final String outputName;

  const MergePdfRequest({
    required this.sourcePaths,
    required this.destinationDirectory,
    required this.outputName,
  });

  @override
  int get hashCode =>
      sourcePaths.hashCode ^
      destinationDirectory.hashCode ^
      outputName.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MergePdfRequest &&
          runtimeType == other.runtimeType &&
          sourcePaths == other.sourcePaths &&
          destinationDirectory == other.destinationDirectory &&
          outputName == other.outputName;
}

enum MergePdfStage { preparing, merging, validating, publishing, completed }

enum MergePdfStatus { running, complete, failed }

class MergePdfUpdate {
  final MergePdfStatus status;
  final MergePdfStage stage;
  final int inputCount;
  final int totalPageCount;
  final String? outputPath;
  final int warningInputCount;
  final bool hasWarnings;
  final int? failedInputIndex;
  final String? failedInputPath;
  final ApplicationError? error;

  const MergePdfUpdate({
    required this.status,
    required this.stage,
    required this.inputCount,
    required this.totalPageCount,
    this.outputPath,
    required this.warningInputCount,
    required this.hasWarnings,
    this.failedInputIndex,
    this.failedInputPath,
    this.error,
  });

  @override
  int get hashCode =>
      status.hashCode ^
      stage.hashCode ^
      inputCount.hashCode ^
      totalPageCount.hashCode ^
      outputPath.hashCode ^
      warningInputCount.hashCode ^
      hasWarnings.hashCode ^
      failedInputIndex.hashCode ^
      failedInputPath.hashCode ^
      error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MergePdfUpdate &&
          runtimeType == other.runtimeType &&
          status == other.status &&
          stage == other.stage &&
          inputCount == other.inputCount &&
          totalPageCount == other.totalPageCount &&
          outputPath == other.outputPath &&
          warningInputCount == other.warningInputCount &&
          hasWarnings == other.hasWarnings &&
          failedInputIndex == other.failedInputIndex &&
          failedInputPath == other.failedInputPath &&
          error == other.error;
}
