// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'error.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`

/// Validates a candidate group without mutating the caller's existing session.
/// The returned additions are all valid; any failure rejects the whole group.
Future<List<OrganizePdfSourceInfo>> inspectOrganizePdfSources({
  required List<String> existingSourcePaths,
  required List<String> candidateSourcePaths,
}) => RustLib.instance.api.crateApiOrganizePdfInspectOrganizePdfSources(
  existingSourcePaths: existingSourcePaths,
  candidateSourcePaths: candidateSourcePaths,
);

/// Organizes one typed multi-source page plan on the native worker pool.
Stream<OrganizePdfUpdate> organizePdf({required OrganizePdfRequest request}) =>
    RustLib.instance.api.crateApiOrganizePdfOrganizePdf(request: request);

class OrganizePdfPageItem {
  final int pageItemId;
  final int sourceId;
  final int sourcePageIndex;
  final OrganizePdfPageRotation rotation;

  const OrganizePdfPageItem({
    required this.pageItemId,
    required this.sourceId,
    required this.sourcePageIndex,
    required this.rotation,
  });

  @override
  int get hashCode =>
      pageItemId.hashCode ^
      sourceId.hashCode ^
      sourcePageIndex.hashCode ^
      rotation.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OrganizePdfPageItem &&
          runtimeType == other.runtimeType &&
          pageItemId == other.pageItemId &&
          sourceId == other.sourceId &&
          sourcePageIndex == other.sourcePageIndex &&
          rotation == other.rotation;
}

enum OrganizePdfPageRotation { none, clockwise90, halfTurn, counterClockwise90 }

class OrganizePdfRequest {
  final List<OrganizePdfSource> sources;
  final List<OrganizePdfPageItem> pageItems;
  final String destinationDirectory;
  final String outputName;

  const OrganizePdfRequest({
    required this.sources,
    required this.pageItems,
    required this.destinationDirectory,
    required this.outputName,
  });

  @override
  int get hashCode =>
      sources.hashCode ^
      pageItems.hashCode ^
      destinationDirectory.hashCode ^
      outputName.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OrganizePdfRequest &&
          runtimeType == other.runtimeType &&
          sources == other.sources &&
          pageItems == other.pageItems &&
          destinationDirectory == other.destinationDirectory &&
          outputName == other.outputName;
}

class OrganizePdfSource {
  final int sourceId;
  final String sourcePath;
  final int pageCount;
  final bool hasWarnings;

  const OrganizePdfSource({
    required this.sourceId,
    required this.sourcePath,
    required this.pageCount,
    required this.hasWarnings,
  });

  @override
  int get hashCode =>
      sourceId.hashCode ^
      sourcePath.hashCode ^
      pageCount.hashCode ^
      hasWarnings.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OrganizePdfSource &&
          runtimeType == other.runtimeType &&
          sourceId == other.sourceId &&
          sourcePath == other.sourcePath &&
          pageCount == other.pageCount &&
          hasWarnings == other.hasWarnings;
}

class OrganizePdfSourceInfo {
  final String sourcePath;
  final int pageCount;
  final bool hasWarnings;

  const OrganizePdfSourceInfo({
    required this.sourcePath,
    required this.pageCount,
    required this.hasWarnings,
  });

  @override
  int get hashCode =>
      sourcePath.hashCode ^ pageCount.hashCode ^ hasWarnings.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OrganizePdfSourceInfo &&
          runtimeType == other.runtimeType &&
          sourcePath == other.sourcePath &&
          pageCount == other.pageCount &&
          hasWarnings == other.hasWarnings;
}

enum OrganizePdfStage {
  preparing,
  organizing,
  validating,
  publishing,
  completed,
}

enum OrganizePdfStatus { running, complete, failed }

class OrganizePdfUpdate {
  final OrganizePdfStatus status;
  final OrganizePdfStage stage;
  final int sourceCount;
  final int pageCount;
  final String? outputPath;
  final int warningSourceCount;
  final bool hasWarnings;
  final int? failedSourceId;
  final String? failedSourcePath;
  final int? failedPageItemId;
  final ApplicationError? error;

  const OrganizePdfUpdate({
    required this.status,
    required this.stage,
    required this.sourceCount,
    required this.pageCount,
    this.outputPath,
    required this.warningSourceCount,
    required this.hasWarnings,
    this.failedSourceId,
    this.failedSourcePath,
    this.failedPageItemId,
    this.error,
  });

  @override
  int get hashCode =>
      status.hashCode ^
      stage.hashCode ^
      sourceCount.hashCode ^
      pageCount.hashCode ^
      outputPath.hashCode ^
      warningSourceCount.hashCode ^
      hasWarnings.hashCode ^
      failedSourceId.hashCode ^
      failedSourcePath.hashCode ^
      failedPageItemId.hashCode ^
      error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OrganizePdfUpdate &&
          runtimeType == other.runtimeType &&
          status == other.status &&
          stage == other.stage &&
          sourceCount == other.sourceCount &&
          pageCount == other.pageCount &&
          outputPath == other.outputPath &&
          warningSourceCount == other.warningSourceCount &&
          hasWarnings == other.hasWarnings &&
          failedSourceId == other.failedSourceId &&
          failedSourcePath == other.failedSourcePath &&
          failedPageItemId == other.failedPageItemId &&
          error == other.error;
}
