// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'application.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `paths_to_strings`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`

/// Exports every page sequentially on flutter_rust_bridge's worker pool and streams progress.
Stream<PdfExportUpdate> exportPdfToImages({
  required ExportPdfToImagesRequest request,
}) => RustLib.instance.api.crateApiPdfExportExportPdfToImages(request: request);

class ExportPdfToImagesRequest {
  final String sourcePath;
  final String destinationDirectory;
  final PdfExportQuality quality;

  const ExportPdfToImagesRequest({
    required this.sourcePath,
    required this.destinationDirectory,
    required this.quality,
  });

  @override
  int get hashCode =>
      sourcePath.hashCode ^ destinationDirectory.hashCode ^ quality.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ExportPdfToImagesRequest &&
          runtimeType == other.runtimeType &&
          sourcePath == other.sourcePath &&
          destinationDirectory == other.destinationDirectory &&
          quality == other.quality;
}

enum PdfExportQuality { standard, highQuality }

enum PdfExportStatus { running, complete, failed }

class PdfExportUpdate {
  final PdfExportStatus status;
  final int totalPageCount;
  final int completedPageCount;
  final int? currentPage;
  final List<String> outputFiles;
  final ApplicationError? error;

  const PdfExportUpdate({
    required this.status,
    required this.totalPageCount,
    required this.completedPageCount,
    this.currentPage,
    required this.outputFiles,
    this.error,
  });

  @override
  int get hashCode =>
      status.hashCode ^
      totalPageCount.hashCode ^
      completedPageCount.hashCode ^
      currentPage.hashCode ^
      outputFiles.hashCode ^
      error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PdfExportUpdate &&
          runtimeType == other.runtimeType &&
          status == other.status &&
          totalPageCount == other.totalPageCount &&
          completedPageCount == other.completedPageCount &&
          currentPage == other.currentPage &&
          outputFiles == other.outputFiles &&
          error == other.error;
}
