// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'error.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`, `from`

Future<ProtectPdfSourceInfo> inspectProtectPdfSource({
  required String sourcePath,
}) => RustLib.instance.api.crateApiPdfSecurityInspectProtectPdfSource(
  sourcePath: sourcePath,
);

Future<UnlockPdfSourceInfo> inspectUnlockPdfSource({
  required String sourcePath,
}) => RustLib.instance.api.crateApiPdfSecurityInspectUnlockPdfSource(
  sourcePath: sourcePath,
);

Stream<ProtectPdfUpdate> protectPdf({required ProtectPdfRequest request}) =>
    RustLib.instance.api.crateApiPdfSecurityProtectPdf(request: request);

Stream<UnlockPdfUpdate> unlockPdf({required UnlockPdfRequest request}) =>
    RustLib.instance.api.crateApiPdfSecurityUnlockPdf(request: request);

enum PdfEncryptionState {
  unencrypted,
  encryptedNoPasswordRequired,
  encryptedPasswordRequired,
}

enum PdfSecurityStatus { running, complete, failed }

class ProtectPdfRequest {
  final String sourcePath;
  final String destinationDirectory;
  final String outputName;
  final String password;
  final String confirmation;

  const ProtectPdfRequest({
    required this.sourcePath,
    required this.destinationDirectory,
    required this.outputName,
    required this.password,
    required this.confirmation,
  });

  @override
  int get hashCode =>
      sourcePath.hashCode ^
      destinationDirectory.hashCode ^
      outputName.hashCode ^
      password.hashCode ^
      confirmation.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProtectPdfRequest &&
          runtimeType == other.runtimeType &&
          sourcePath == other.sourcePath &&
          destinationDirectory == other.destinationDirectory &&
          outputName == other.outputName &&
          password == other.password &&
          confirmation == other.confirmation;
}

class ProtectPdfSourceInfo {
  final String sourcePath;
  final int? pageCount;
  final BigInt sizeBytes;
  final PdfEncryptionState encryptionState;
  final bool hasWarnings;
  final String defaultOutputName;

  const ProtectPdfSourceInfo({
    required this.sourcePath,
    this.pageCount,
    required this.sizeBytes,
    required this.encryptionState,
    required this.hasWarnings,
    required this.defaultOutputName,
  });

  @override
  int get hashCode =>
      sourcePath.hashCode ^
      pageCount.hashCode ^
      sizeBytes.hashCode ^
      encryptionState.hashCode ^
      hasWarnings.hashCode ^
      defaultOutputName.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProtectPdfSourceInfo &&
          runtimeType == other.runtimeType &&
          sourcePath == other.sourcePath &&
          pageCount == other.pageCount &&
          sizeBytes == other.sizeBytes &&
          encryptionState == other.encryptionState &&
          hasWarnings == other.hasWarnings &&
          defaultOutputName == other.defaultOutputName;
}

enum ProtectPdfStage {
  preparing,
  protecting,
  validating,
  publishing,
  completed,
}

class ProtectPdfUpdate {
  final PdfSecurityStatus status;
  final ProtectPdfStage stage;
  final int pageCount;
  final String? outputPath;
  final bool hasWarnings;
  final ApplicationError? error;

  const ProtectPdfUpdate({
    required this.status,
    required this.stage,
    required this.pageCount,
    this.outputPath,
    required this.hasWarnings,
    this.error,
  });

  @override
  int get hashCode =>
      status.hashCode ^
      stage.hashCode ^
      pageCount.hashCode ^
      outputPath.hashCode ^
      hasWarnings.hashCode ^
      error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProtectPdfUpdate &&
          runtimeType == other.runtimeType &&
          status == other.status &&
          stage == other.stage &&
          pageCount == other.pageCount &&
          outputPath == other.outputPath &&
          hasWarnings == other.hasWarnings &&
          error == other.error;
}

class UnlockPdfRequest {
  final String sourcePath;
  final String destinationDirectory;
  final String outputName;
  final String? password;

  const UnlockPdfRequest({
    required this.sourcePath,
    required this.destinationDirectory,
    required this.outputName,
    this.password,
  });

  @override
  int get hashCode =>
      sourcePath.hashCode ^
      destinationDirectory.hashCode ^
      outputName.hashCode ^
      password.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UnlockPdfRequest &&
          runtimeType == other.runtimeType &&
          sourcePath == other.sourcePath &&
          destinationDirectory == other.destinationDirectory &&
          outputName == other.outputName &&
          password == other.password;
}

class UnlockPdfSourceInfo {
  final String sourcePath;
  final int? pageCount;
  final BigInt sizeBytes;
  final PdfEncryptionState encryptionState;
  final bool hasWarnings;
  final String defaultOutputName;

  const UnlockPdfSourceInfo({
    required this.sourcePath,
    this.pageCount,
    required this.sizeBytes,
    required this.encryptionState,
    required this.hasWarnings,
    required this.defaultOutputName,
  });

  @override
  int get hashCode =>
      sourcePath.hashCode ^
      pageCount.hashCode ^
      sizeBytes.hashCode ^
      encryptionState.hashCode ^
      hasWarnings.hashCode ^
      defaultOutputName.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UnlockPdfSourceInfo &&
          runtimeType == other.runtimeType &&
          sourcePath == other.sourcePath &&
          pageCount == other.pageCount &&
          sizeBytes == other.sizeBytes &&
          encryptionState == other.encryptionState &&
          hasWarnings == other.hasWarnings &&
          defaultOutputName == other.defaultOutputName;
}

enum UnlockPdfStage { preparing, unlocking, validating, publishing, completed }

class UnlockPdfUpdate {
  final PdfSecurityStatus status;
  final UnlockPdfStage stage;
  final int pageCount;
  final String? outputPath;
  final bool hasWarnings;
  final ApplicationError? error;

  const UnlockPdfUpdate({
    required this.status,
    required this.stage,
    required this.pageCount,
    this.outputPath,
    required this.hasWarnings,
    this.error,
  });

  @override
  int get hashCode =>
      status.hashCode ^
      stage.hashCode ^
      pageCount.hashCode ^
      outputPath.hashCode ^
      hasWarnings.hashCode ^
      error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UnlockPdfUpdate &&
          runtimeType == other.runtimeType &&
          status == other.status &&
          stage == other.stage &&
          pageCount == other.pageCount &&
          outputPath == other.outputPath &&
          hasWarnings == other.hasWarnings &&
          error == other.error;
}
