// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'error.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`

/// Inspects a local PDF. The path remains on this machine and is never logged.
Future<PdfDocumentInfo> openPdfDocument({required String sourcePath}) => RustLib
    .instance
    .api
    .crateApiPdfPreviewOpenPdfDocument(sourcePath: sourcePath);

/// Renders one zero-based page through the Rust PDF infrastructure.
Future<RenderPdfPageResult> renderPdfPage({
  required RenderPdfPageRequest request,
}) => RustLib.instance.api.crateApiPdfPreviewRenderPdfPage(request: request);

class PdfDocumentInfo {
  final int pageCount;
  final PdfPageSize? firstPageSize;

  const PdfDocumentInfo({required this.pageCount, this.firstPageSize});

  @override
  int get hashCode => pageCount.hashCode ^ firstPageSize.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PdfDocumentInfo &&
          runtimeType == other.runtimeType &&
          pageCount == other.pageCount &&
          firstPageSize == other.firstPageSize;
}

class PdfPageSize {
  final double widthPoints;
  final double heightPoints;

  const PdfPageSize({required this.widthPoints, required this.heightPoints});

  @override
  int get hashCode => widthPoints.hashCode ^ heightPoints.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PdfPageSize &&
          runtimeType == other.runtimeType &&
          widthPoints == other.widthPoints &&
          heightPoints == other.heightPoints;
}

class RenderPdfPageRequest {
  final String sourcePath;
  final int pageIndex;
  final int targetWidth;
  final String? destinationPath;

  const RenderPdfPageRequest({
    required this.sourcePath,
    required this.pageIndex,
    required this.targetWidth,
    this.destinationPath,
  });

  @override
  int get hashCode =>
      sourcePath.hashCode ^
      pageIndex.hashCode ^
      targetWidth.hashCode ^
      destinationPath.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RenderPdfPageRequest &&
          runtimeType == other.runtimeType &&
          sourcePath == other.sourcePath &&
          pageIndex == other.pageIndex &&
          targetWidth == other.targetWidth &&
          destinationPath == other.destinationPath;
}

class RenderPdfPageResult {
  final String outputPath;
  final int widthPixels;
  final int heightPixels;

  const RenderPdfPageResult({
    required this.outputPath,
    required this.widthPixels,
    required this.heightPixels,
  });

  @override
  int get hashCode =>
      outputPath.hashCode ^ widthPixels.hashCode ^ heightPixels.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RenderPdfPageResult &&
          runtimeType == other.runtimeType &&
          outputPath == other.outputPath &&
          widthPixels == other.widthPixels &&
          heightPixels == other.heightPixels;
}
