// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'error.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `failed_update`, `to_core_mode`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`

Future<SplitPdfSourceInfo> inspectSplitPdfSource({
  required String sourcePath,
}) => RustLib.instance.api.crateApiSplitPdfInspectSplitPdfSource(
  sourcePath: sourcePath,
);

Stream<SplitPdfUpdate> splitPdf({required SplitPdfRequest request}) =>
    RustLib.instance.api.crateApiSplitPdfSplitPdf(request: request);

enum SplitPdfMode { everyPage, everyNPages, splitAfterPages, maximumFileSize }

class SplitPdfPart {
  final String outputPath;
  final int firstPage;
  final int lastPage;
  final BigInt sizeBytes;

  const SplitPdfPart({
    required this.outputPath,
    required this.firstPage,
    required this.lastPage,
    required this.sizeBytes,
  });

  @override
  int get hashCode =>
      outputPath.hashCode ^
      firstPage.hashCode ^
      lastPage.hashCode ^
      sizeBytes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SplitPdfPart &&
          runtimeType == other.runtimeType &&
          outputPath == other.outputPath &&
          firstPage == other.firstPage &&
          lastPage == other.lastPage &&
          sizeBytes == other.sizeBytes;
}

class SplitPdfRequest {
  final String sourcePath;
  final String destinationDirectory;
  final SplitPdfMode mode;
  final int? everyNPages;
  final String? splitAfterPages;
  final BigInt? maximumSizeMb;

  const SplitPdfRequest({
    required this.sourcePath,
    required this.destinationDirectory,
    required this.mode,
    this.everyNPages,
    this.splitAfterPages,
    this.maximumSizeMb,
  });

  @override
  int get hashCode =>
      sourcePath.hashCode ^
      destinationDirectory.hashCode ^
      mode.hashCode ^
      everyNPages.hashCode ^
      splitAfterPages.hashCode ^
      maximumSizeMb.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SplitPdfRequest &&
          runtimeType == other.runtimeType &&
          sourcePath == other.sourcePath &&
          destinationDirectory == other.destinationDirectory &&
          mode == other.mode &&
          everyNPages == other.everyNPages &&
          splitAfterPages == other.splitAfterPages &&
          maximumSizeMb == other.maximumSizeMb;
}

class SplitPdfSourceInfo {
  final int pageCount;
  final BigInt sizeBytes;
  final bool hasWarnings;

  const SplitPdfSourceInfo({
    required this.pageCount,
    required this.sizeBytes,
    required this.hasWarnings,
  });

  @override
  int get hashCode =>
      pageCount.hashCode ^ sizeBytes.hashCode ^ hasWarnings.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SplitPdfSourceInfo &&
          runtimeType == other.runtimeType &&
          pageCount == other.pageCount &&
          sizeBytes == other.sizeBytes &&
          hasWarnings == other.hasWarnings;
}

enum SplitPdfStage {
  preparing,
  findingSplitPoints,
  creating,
  validating,
  publishing,
  completed,
}

enum SplitPdfStatus { running, complete, failed }

class SplitPdfUpdate {
  final SplitPdfStatus status;
  final SplitPdfStage stage;
  final int sourcePageCount;
  final int? currentPart;
  final int? totalParts;
  final String? outputDirectory;
  final List<SplitPdfPart> parts;
  final bool hasWarnings;
  final int? failedPageNumber;
  final BigInt? actualSizeBytes;
  final BigInt? limitSizeBytes;
  final ApplicationError? error;

  const SplitPdfUpdate({
    required this.status,
    required this.stage,
    required this.sourcePageCount,
    this.currentPart,
    this.totalParts,
    this.outputDirectory,
    required this.parts,
    required this.hasWarnings,
    this.failedPageNumber,
    this.actualSizeBytes,
    this.limitSizeBytes,
    this.error,
  });

  @override
  int get hashCode =>
      status.hashCode ^
      stage.hashCode ^
      sourcePageCount.hashCode ^
      currentPart.hashCode ^
      totalParts.hashCode ^
      outputDirectory.hashCode ^
      parts.hashCode ^
      hasWarnings.hashCode ^
      failedPageNumber.hashCode ^
      actualSizeBytes.hashCode ^
      limitSizeBytes.hashCode ^
      error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SplitPdfUpdate &&
          runtimeType == other.runtimeType &&
          status == other.status &&
          stage == other.stage &&
          sourcePageCount == other.sourcePageCount &&
          currentPart == other.currentPart &&
          totalParts == other.totalParts &&
          outputDirectory == other.outputDirectory &&
          parts == other.parts &&
          hasWarnings == other.hasWarnings &&
          failedPageNumber == other.failedPageNumber &&
          actualSizeBytes == other.actualSizeBytes &&
          limitSizeBytes == other.limitSizeBytes &&
          error == other.error;
}
